### ISSUE TITLE
Unique Damage Level Per Weapon

### ISSUE THREAD

**Issue by biscuut** [mcmonkeyprojects/Sentinel#125]
Maybe a syntax like this /sentinel damage (number) (material)
If the material isn't specified then that will be the default damage
If a material doesn't have a specific damage for its item, then it will use the default
However if it does, it will override the default.
🙂

**Comment by mcmonkey4eva** [comment]
Sorry for not giving an actual reply sooner:
I haven't tried this yet as that would be a lot of data-management stuff (Convincing a map to persist properly mainly) and so I've been slow about this...

**Comment by mcmonkey4eva** [comment]
Sorry for taking literally two and a half years to do this, but uh... added! :D
`/sentinel weapondamage MATERIAL DAMAGE` is now available, like `/sentinel weapondamage diamond_sword 50`.

**Comment by biscuut** [comment]
@mcmonkey4eva hahaha you're a legend. 2017 and still got to it, thank you! 😂
