### ISSUE TITLE
Target group?

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkeyprojects/Sentinel#132]
Heyho,

I have a question. In the readme you wrote, I could add a group as target with group:GROUPNAME. But how can I define, who is in this group?

**Comment by mcmonkey4eva** [comment]
That's a Vault-based permission group.

**Comment by Firemonkey08** [comment]
Thanks. Do you mean, you could set groups as target, I can put NPCs in? On our Server we want to do a big battle against NPCs, and we have some NPC friends. Now I´ve filled the targets and ignoretargets with the name, all enemies have the name --Name-- and all friends ~~Name~~. But it would be cool, if I can easily put some NPCs in one group and set the group as target.

**Comment by mcmonkey4eva** [comment]
You can use the Sentinel squad system to share targets.
I could make a valid squad: target if that helps your case.

**Comment by Firemonkey08** [comment]
This would be great :)

**Comment by Firemonkey08** [comment]
That isn´t so important, cause I can use the names as target. You can close this enhancement, if you want.

**Comment by mcmonkey4eva** [comment]
I forgot to post here, the `squad:` target was added a while back.
