### ISSUE TITLE
Support Enderdragon/Flying Mob Sentinel NPCs

### ISSUE THREAD

**Issue by bilel-lm** [mcmonkeyprojects/Sentinel#162]
Hi,
My npc which is an enderdragon only attack me when i'm flying above it can you fix it ?

thanks,
SNW

**Comment by mcmonkey4eva** [comment]
Enderdragon combat AI hasn't been written for Sentinel yet >.>

Sentinel AI is currently designed only for ground combat

**Comment by SNWarbard** [comment]
Oh okay thank you

**Comment by mcmonkey4eva** [comment]
I didn't say it wouldn't happen, just it hasn't been done yet.

**Comment by 123123b** [comment]
Would be nice if Sentinels can attack in the air + do ranged attacks in the air. 

I **might** be able to help @mcmonkey4eva with this issue in this summer once I finish my java course. But all I can say now is that maybe Enderdragon attacks will be similar to bats. Like a hit-and-run type of attack. If they are ranged AND flying, then it would be best to add an option for them to standstill and shoot at you or move while shooting.
