### ISSUE TITLE
Sneak

### ISSUE THREAD

**Issue by JennaDiamonds** [mcmonkeyprojects/Sentinel#185]
Using 1.11.2 spigot and latest builds from citizen/sentinel

When players use an invisibility potion, the sentinels can still detect them.
Can this be fixed please? :)

**Comment by Rkaynjehll** [comment]
I'm willing to pay for this enhancement if it's not something you're planning to add.

**Comment by mcmonkey4eva** [comment]
I'm probably going to add it sometime soon actually, as it sounds interesting.

Haven't been able to focus on minecraft modwork much recently, but when I get time this is one of the more fun ones to do.

... Would still appreciate a donation anyway though, once it's done :P

**Comment by Rkaynjehll** [comment]
I hope you'll have some free time in the near future. I've been working hard on an MMORPG and sentinels are what I use as enemies. If this is added then I'll be able to add a stealth ability to my current "thief" class.

... Would still donate either way, once it's done :P haha

**Comment by mcmonkey4eva** [comment]
Added :)
Try build 129+ dev release. http://ci.citizensnpcs.co/job/Sentinel/
Lemme know how well it works for you!

Also if you want to donate, use https://one.denizenscript.com/donate

**Comment by Rkaynjehll** [comment]
Working very well! They still look at me when i get close to them, but i think this is a citizens 2 issue. Correct me if I am wrong though.
Thank you so much for adding this enhancement, i'll visit the donate link :)

**Comment by mcmonkey4eva** [comment]
That might be the `lookclose` trait at work? `/npc lookclose`

**Comment by Rkaynjehll** [comment]
it is, and i toggled it off with /npc lookclose
working much better now. However when fighting on stairs, some funky things happen with the sentinel's head. Rather funny actually they look like a bobble-head at times haha
But it works good enough for me at this point. Thank you for all your help. :)

**Comment by JennaDiamonds** [comment]
I'm not sure what has changed with the new builds, but sentinels are back to targeting me while using an invisibility potion. Tried using /sentinel realistic and it didn't work. Can this be fixed? :)

**Comment by mcmonkey4eva** [comment]
Tested locally, Spigot 1.14.4 + Sentinel 2.0.0 build 314 - NPC isn't able to spot me if I sneak past while invisible.

It's not controlled by 'realistic' mode, it's a separate config option. When that config option is enabled, and a player is:
- Invisible (by potion)
- Not already a target of the NPC
- Not wearing any equipment or carrying items (as these are visible)

the NPC will not target that player.

**Comment by JennaDiamonds** [comment]
On my older server(1.11.2) my players could wear armor/weapons and even be in the middle of combat and use invisibility and sneak past them. Was that a bug? lol
I'm running an MMORPG in minecraft basically, using sentinels as custom enemies. Right now the skills/spells/items that grant invisibility have become unusable since I updated to 1.13.2(other plugins aren't quite rdy on 1.14) 

A few mins of testing later: Spigot 1.13.2 + Sentinel 1.9.9 b305
-Sentinels are detecting me using invisibility and completely naked with nothing in my hands.

A few more mins: Spigot 1.13.2 + Sentinel 2.0.0 b314
-After updating to dev build, it is functioning as you described.

Is there a way to make them ignore invisible players wearing armor and having weapons in their hands? Maybe a future feature? Would really like to have it work like it did on 1.11.2 :)

**Comment by JennaDiamonds** [comment]
Tried using plugins like Invisibility+ and SuperVanish as a temporary workaround. Even while using those, the sentinel detects me when i have something in my hands or wearing armor :(

**Comment by mcmonkey4eva** [comment]
`On my older server(1.11.2) my players could wear armor/weapons and even be in the middle of combat and use invisibility and sneak past them. Was that a bug? lol`
That'd have been a bug, yes. Invisibility should only work when a player is actually invisible... wearing armor or holding an item makes you super visible (and punching an NPC while invisible would be too cheaty if it didn't start fighting back at that point).

`Is there a way to make them ignore invisible players wearing armor and having weapons in their hands? Maybe a future feature?`
I could add a feature for that, if you think that makes sense on your server (from a reasonableness for players perspective). I'd argue it doesn't make any sense for a normal server, but if you're using some custom spells/similar instead of just the classic minecraft 8 minutes of unlimited invisibility potion, might make more sense.

**Comment by JennaDiamonds** [comment]
I totally understand that it wouldn't make much sense for a more survival/vanilla styled server, but for mine, it would really help a lot if implementation were possible. To give some insight: Players in my server are able to use custom castable skills, like "shield bash", "volley of arrows" and cast combos.. Like if they cast a fire wall on the ground, and shoot an arrow through it, that arrows becomes a flaming arrow... Another cast skill is "Sneak;" At low level it gives the player invisibility for 3 seconds with a mana cost and cooldown (similar to games like wow or eso). When they use the sneak skill, I'd like them to be able to temporarily break free of combat to heal, regroup, drink potions or whatever their creative minds can come up with.
All that being said, if you could add the feature as a possibility, I'd be greatful :)

**Comment by mcmonkey4eva** [comment]
Via the commit above, with new dev builds, you can do `/sentinel addignore potion:invisibility` and it should achieve exactly what you need!
