### ISSUE TITLE
Feature Request: SimpleClans Integration

### ISSUE THREAD

**Issue by Pawned** [mcmonkeyprojects/Sentinel#195]
Hello,

It would be awesome if you could integrate with SimpleClans, so that like Factions you could set the Sentinal to target all players from a certain clan.

**Comment by mcmonkey4eva** [comment]
Hi there! I added initial support for SimpleClans!
It's difficult for me to test some plugin integrations without having a ton of accounts to try with, but it should work.

It's available in build DEV-139+ on http://ci.citizensnpcs.co/job/Sentinel/

Lemme know how it goes!
