### ISSUE TITLE
Splash potions not working on sentinels with PVP restrictions

### ISSUE THREAD

**Issue by Blamo27** [mcmonkeyprojects/Sentinel#197]
Hello, 

As you know, "enforce damage" option allows us to damage sentinels that are in PVP-restricted areas. However, that doesn't allow the player to use splash or lingering potions against sentinels, the effects of these potions are still blocked by the PVP restriction. It would be perfect if you could add that possibility to the "enforce damage" option.

Thank you.

**Comment by mcmonkey4eva** [comment]
Don't know why I didn't reply about this before, but:

To my memory there isn't any option that enables players damaging an NPC if blocked.
(Enforce damage is for the NPC to damage players through blocks.)

I'd imagine NPCs just don't take effect from splash potions at all right now.

**Comment by Ferocimo** [comment]
That's correct, we didn't test this without enforce damage but indeed, NPCs don't take damages from splash potions.

**Comment by mcmonkey4eva** [comment]
As was mentioned, there is literally no option in Sentinel config or elsewhere that allows NPCs to take damage in no-PvP areas - the fact that NPCs can be damaged at all indicates that the no-PvP area is not preventing NPC damage in the first place, and is not a related issue.

It's also possible the no-PvP plugin has made special exceptions to allow some NPCs to receive damage but not others - if so, talk to the developers of that plugin about that.

There might be some much more general issue with NPCs not being damaged by potions - if so, that would constitute a Citizens issue, not Sentinel.
