### ISSUE TITLE
StandStill suggestion

### ISSUE THREAD

**Issue by 123123b** [mcmonkeyprojects/Sentinel#214]
I have a new feature to suggest.

You know how sentinels keep running towards a player with a ranged weapon (gun, bow, etc) no matter how far or close they are to you? Eventually, it seems silly if they try to shoot you 1 block away while still running to you. I think it would be much better to implement a command to make the sentinel stand a certain amount of blocks away from the player to shoot them. If they have chaseranged on, they will run towards the player, then stop to what the sentinel owner put it to

For an example:
Sentinel Bok has chase ranged on, and is using a gun. He sees a player and starts running while shooting towards him.
However, prior to this, the player Bill has put a restriction to where the sentinel will get no closer to the player while holding a ranged weapon. He will not go beyond 10 blocks when near a player
Bok continues to run towards the enemy. He finds out that he's 10 blocks close to him, and no longer continues to advance to him. He still shoots, just doesn't continue walking towards the player, unless they run away from him.
If Bok has autoswitch on, and if the player is close enough, he will switch to his melee weapon
(optional) If the player gets closer to Bok, Bok will walk back slowly to try to supplement for the amount of blocks he is close to the player.

**Comment by mcmonkey4eva** [comment]
As of the latest update (Sentinel v1.7.6) you can accomplish this by setting `/sentinel avoidrange 10` and `/sentinel addavoid [...]` on each target you want the NPC to stay back from.
