### ISSUE TITLE
Run away

### ISSUE THREAD

**Issue by 123123b** [mcmonkeyprojects/Sentinel#219]
You know how when ocelots run away from you when you try to get near them? Why not make a feature the same for the Sentinels? Make them fear an entity, group, npc, etc. When they see them, they will attempt to runaway from their pursuer. If they are in combat and they see that this entity they are afraid of is coming towards them, they should runaway.

The command should be very similar to adding, removing, and viewing targets.
Like /sentinel addRunaway Zombie, /sentinel removeRunaway NPC:Bob

I'm want to make a quest where players need to chase down a some enemies, so this would be great if this gets added

**Comment by mcmonkey4eva** [comment]
That sounds like a cool feature! I'm adding this to the plans!

**Comment by TheRealWHfan** [comment]
Good idea, be great if it was added as a feature.

**Comment by mcmonkey4eva** [comment]
I think #214 and this go together a bit, and a good solution might add both in one go.

Some standard system of holding a certain distance away from targets - whether that's running away from a threat or just keeping back while fighting.

**Comment by shawngiese** [comment]
Or run to a location... like spies, or thieves watching a path.

**Comment by shawngiese** [comment]
I was thinking that the sentinel would guard an area but when it saw say two target creatures it would trigger something like run and get help, or call out 'intruders, intruders' that could trigger others NPCs to come. Or if they were thieves and saw more than one person (maybe with a diamond) they could go get some more friends to attack. 

Could make a fun dynamic so when the players figured it out they could send one person to draw off the group and then go raid their camp.

**Comment by mcmonkey4eva** [comment]
@shawngiese sorry for late reply-
That'd be a fun thing to have. Can you please open that as a new issue? That'd be a separate system to build from this request.

**Comment by mcmonkey4eva** [comment]
As of the latest update (Sentinel v1.7.6) you can accomplish this feature via `/sentinel addavoid [...]` (and `removeavoid`) and `/sentinel avoidrange [...]`.
You might also use `/sentinel runaway true` to make an NPC automatically run away when attacked.

**Comment by mcmonkey4eva** [comment]
@shawngiese Yes, as 1.7.6 does what this issue post (from @123123b ) was requesting, and not what you were requesting.
