### ISSUE TITLE
SentinelAttackOverEvent suggestion

### ISSUE THREAD

**Issue by LuckyClutch07** [mcmonkeyprojects/Sentinel#266]
I have looked into it and i got the idea on how to add the event but i cant commit/push or PR or anything, i'm kinda new to the git repository thing, What i did was made a check on the event EntityDeathEvent(whenAnEnemyDies) for the currentTargets if their empty then call out an event just like SentinelAttackEvent but with a different name and it should do the trick now i don't know if there is another method that automatically forgives/dismisses the targets if so then you should know where to find it i guess then just make another check in there and it should work like a charm and it can come in handy at least for me rn i need it to send the sentinel back to it's location even tho i can do it with the path but i want to have more control over the plugin and kindof make it more automated i guess.

**Comment by mcmonkey4eva** [comment]
As of latest build (DEV-225+) the `SentinelNoMoreTargetsEvent` is available, and will fire whenever a Sentinel has no more targets remaining. This can happen either if an enemy dies, or enemies go out of range and are no longer a threat.
