### ISSUE TITLE
Help! NPC drops drops after death in only one world

### ISSUE THREAD

**Issue by Noob1917** [mcmonkeyprojects/Sentinel#267]
Help! NPC drops drops after death in only one world

**Comment by mcmonkey4eva** [comment]
What?

- Figure out what's different between worlds (If you use a worldmanager like Multiverse, that's likely something to look into as a potential blockage)
Consider using the `workaround drops` config option ( https://github.com/mcmonkeyprojects/Sentinel/blob/master/src/main/resources/config.yml#L49-L50 )

**Comment by Noob1917** [comment]
Yes I use Multiverse-core? but what do I do ? if what to do in the config ? I don't know what ?

**Comment by mcmonkey4eva** [comment]
Figure out what's blocking drops in one world or the other.

If you choose to instead use the config option I mentioned, just change it to `true` instead of `false` on your server

**Comment by Noob1917** [comment]
and why enchanted things marks without enchantment
