### ISSUE TITLE
Exception onEnable

### ISSUE THREAD

**Issue by Ytnoos** [mcmonkeyprojects/Sentinel#269]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1591)
The output of command `/version sentinel` on my server is: Sentinel version 1.6.2 (build 191)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/VZL7Ydyd

Error log:
https://pastebin.com/GKQVm64s

**Comment by mcmonkey4eva** [comment]
That bug was already fixed in a recent dev build! You can download that here: http://ci.citizensnpcs.co/job/Sentinel/
