### ISSUE TITLE
FollowClose

### ISSUE THREAD

**Issue by brooklynstarr** [mcmonkeyprojects/Sentinel#272]
Hey,

Using Sentinel Sentinel-1.7.6-b203 with Paper 1.13.2-488. With this new update (Sentinel), I'm no longer able to deal damage to my own bodyguard. This was useful because the guard always teleports into you and this is quite annoying. Back in the Sentry days, there used to be a "followclose" command that would tell the guard how far behind you to follow. Right now the Sentinel is on me like white on rice, and even pushes me as soon as he gets close- annoying while building especially.

So there are 2 requests: 

1) Can we go back to being able to hurt our own bodyguards?

2) Can we get a "follow close" command that tells the Sentinel how far to keep its distance from us at any time?

If this already exists, please let me know- I've checked the command structure and cannot find any such command.

Thanks.

**Comment by mcmonkey4eva** [comment]
Relevant settings here: https://github.com/mcmonkeyprojects/Sentinel/blob/master/src/main/resources/config.yml#L78-L85
You may also want to check the `use-new-finder` setting in Citizens (when it's set `true` NPC pathfinding tends to be more intelligent, including obeying distance margins)
Theoretically with that enabled and the config settings set reasonably, the NPC should never run into you (you may in particular want a rather high margin to be safest on that)

**Comment by brooklynstarr** [comment]
This works, thanks. Now I've got good distance and the guard is no longer in my way. It would be nice to have a command though, this way I won't have to reload the server each time I make changes. On that note, a "/sentinel reload" command would be nice to have. I do like the new command structure though, thanks for adding this.

As always, appreciate the help!

**Comment by mcmonkey4eva** [comment]
As of build DEV-219+,
There's now a `/sentinel reload` command available.

Additionally, there's now a `no guard damage: true` option in the config - set this to `false` to satisfy your request `Can we go back to being able to hurt our own bodyguards?`

**Comment by mcmonkey4eva** [comment]
And as of build DEV-220+ you can as well use `/sentinel guarddistance` to set the guarddistance on a single NPC at any time.
I believe this completes everything you've requested here.

Please let me know if there's anything missing or not working
