### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by Straiker123** [mcmonkeyprojects/Sentinel#273]
No screenshots

1.12.2-R0.1-SNAPSHOT
2.0.24-SNAPSHOT - Build 1591
1.7.5 - Build 202
https://pastebin.com/BARYqyt7

Hello i have question.
How i set money to sentinel if i kill npc ?

**Comment by mcmonkey4eva** [comment]
Er...
- Option A: Add some currency item into `/sentinel drops` (some item worth a given amount of currency that can be traded for that in a town or whatever applies)
- Option B: Get some generic money-looting plugin setup that works with NPCs
- Option C: Use something like Denizen ( https://www.spigotmc.org/resources/denizen.21039/ ) and write a fairly straightforward script to handle giving currency rewards for killing NPCs (if you choose this option, join us on the Sentinel+Citizens+Denizen team discord, we can guide ya through setting up the script)

**Comment by Straiker123** [comment]
I will not download the next plugin.
I solved the problem by putting the drops in front and adding the item to the shop for sale.
