### ISSUE TITLE
I can't kill npc

### ISSUE THREAD

**Issue by Straiker123** [mcmonkeyprojects/Sentinel#274]
![2019-01-12_18 02 56](https://user-images.githubusercontent.com/43417249/51076086-56476080-1694-11e9-9bf5-c16ee6402962.png)
![2019-01-12_18 02 59](https://user-images.githubusercontent.com/43417249/51076087-56476080-1694-11e9-93d4-a74ab10d5364.png)

Server version: 1.12.2-R0.1-SNAPSHOT
Citizens version: 2.0.24-SNAPSHOT (build 1591)
Sentinel version: 1.6.2 (build 191)
Config:

[config.zip](https://github.com/mcmonkeyprojects/Sentinel/files/2752294/config.zip)

Hello, I have a problem with Sentinel .. Every time I set the whole npc (i sentinel) at selected NPC and npc citizen can not kill even Sentinel kill ..
so I want to ask if this is a bug on my side or a plugin error

                                                                    **No errors**

**Comment by mcmonkey4eva** [comment]
That's a particularly obtuse way of posting a config. Use pastebin: https://pastebin.com/ for text file pastes.

You're running outdated versions, please update Spigot to latest 1.12.2 via BuildTools, Citizens to latest dev via http://ci.citizensnpcs.co/job/Citizens2/ and Sentinel to latest dev via http://ci.citizensnpcs.co/job/Sentinel/

If the issue persists on latest versions:

Check `/sentinel info` to see whether the NPC's health is changing (if it's staying at full health or dropping but not all the way to 0).
It's quite possible an unrelated plugin is interfering - particularly any plugins that alter how combat works on the server (eg one that increases damage by leveling up a skill, or one that blocks damaging entities in no-combat areas, ...)
If you have plugins like this, test whether any of them seem to be the source of the issue - follow the steps here: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by Straiker123** [comment]
latest dev build repaired it bug
