### ISSUE TITLE
Sentinel teleports NPCs

### ISSUE THREAD

**Issue by Straiker123** [mcmonkeyprojects/Sentinel#275]
![2019-01-12_18 47 13](https://user-images.githubusercontent.com/43417249/51076583-a2959f00-169a-11e9-8697-1cc9cbb7ee48.png)
![2019-01-12_18 47 15](https://user-images.githubusercontent.com/43417249/51076584-a2959f00-169a-11e9-9ee4-9b878293783d.png)
![2019-01-12_18 47 20](https://user-images.githubusercontent.com/43417249/51076585-a32e3580-169a-11e9-8f31-754ab9fbf84a.png)
![2019-01-12_18 47 23](https://user-images.githubusercontent.com/43417249/51076586-a32e3580-169a-11e9-940c-130ed6cbc8ce.png)

Server version: 1.12.2-R0.1-SNAPSHOT
Citizens version: 2.0.24-SNAPSHOT (build 1591)
Sentinel version: 1.7.6 (build 207)

Hello i have problem with plugin sentinel..
NPCs are teleported by sentinel !
They have a specified path in / npc path ..
Each time 5 blocks go and teleports 20 blocks away.
Please fix it ! :(
Thank you.

**Comment by mcmonkey4eva** [comment]
I'm not sure I entirely understand.

Are you saying:
NPCs are following a path set by `/npc path`, and as they walk along they suddenly teleport ahead of themselves?

If so: have you tested whether that still happens when NPCs do not have the sentinel trait?

See also the bit about updating on your other issue #274

**Comment by Straiker123** [comment]
if i set /trait sentinel off npc path working without problems

**Comment by mcmonkey4eva** [comment]
How long are the paths they're set to take? Like, from one point to the next how far exactly do they need to go? (number of blocks walked over)

**Comment by Straiker123** [comment]
7 - 12

**Comment by Straiker123** [comment]
if I set 2-4 block so I did not teleport

**Comment by tap3w0rm** [comment]
I am having the same issue 1.13.2 spigot

Short paths like markers every 2 to 3 squares ... no problem. Other than that they either teleport from one point to the next or just sit there and walk in a circle and never move off their squares. Other npc's dont have this issue.

**Comment by Straiker123** [comment]
:+1:

**Comment by mcmonkey4eva** [comment]
I cannot replicate any issues here.

I would note that there's a Citizens functionality known as _pathrange_, which specifies how far an NPC is able to walk before it teleports. If you're setting path points longer than the pathrange, it will of course teleport.
The default pathrange value is 25, and you can change it via `/npc pathrange`

My best guess is that you're encountering the pathrange limit here, there doesn't seem to be anything wrong with pathfinding in my testing.

There were separate problems with pathfinding recently, if the pathrange check doesn't suffice please ensure you're running latest Sentinel: https://ci.citizensnpcs.co/job/Sentinel/ (build 216 or newer)
And latest Citizens: https://ci.citizensnpcs.co/job/Sentinel/ (build 1624 or newer)
And latest Spigot/Paper for 1.12.2 or 1.13.2 (Use `/version` - if it says "You are [x] builds behind" please update)
