### ISSUE TITLE
Squad targeting not working 

### ISSUE THREAD

**Issue by Steffbeard** [mcmonkeyprojects/Sentinel#276]
/version: 

13.01 10:15:35 [Server] INFO This server is running CraftBukkit version git-Spigot-7d78b81-a867313 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
13.01 10:15:35 [Server] INFO You are 805 version(s) behind

/version citizens:

13.01 10:16:04 [Server] INFO Citizens version 2.0.24-SNAPSHOT (build 1604)
13.01 10:16:04 [Server] INFO Website: http://www.citizensnpcs.co
13.01 10:16:04 [Server] INFO Authors: aPunch and fullwall

/version sentinel:

13.01 10:16:46 [Server] INFO Sentinel version 1.6.2 (build 191)
13.01 10:16:46 [Server] INFO Author: mcmonkey

[pastebin link to my config.yml](https://pastebin.com/h2HTJHHM)

Hello, this plugin is amazing and really good job with it!

This command:
/sentinel addtarget squad:SQUADNAME

Doesn't seem to work for me as the sentinel just stands there even when target squad member is within range. Not spitting any errors in console either.

I also have a question as to is there a way to make the guards/soldiers walk in formation? Or do you have to use Citizens for that? 

Is there a way to select an entire squad? I know you said before in an earlier issue that I opened that multi-selection is not supported by Citizens yet.

**Comment by mcmonkey4eva** [comment]
That's a newer feature of Sentinel - need to run a newer build of Sentinel to have it: http://ci.citizensnpcs.co/job/Sentinel/
Also I strongly recommend updating that Spigot server, ideally to 1.12.2 or 1.13.2, but at the very least the most up-to-date version of 1.11.2

`I also have a question as to is there a way to make the guards/soldiers walk in formation?` at the moment, no. Would require some fancy tricks with the pathfinder, and would likely just look awkward in minecraft (consider a simple 3 man triangle formation: 1 center forward and 2 off to the sides behind... the two on the side will be jumping up and down trying to keep position but getting messed up by Minecraft's horrifically uneven terrain)

`Is there a way to select an entire squad?` Nope. Multi-select would be something for Citizens to add.

**Comment by Steffbeard** [comment]
Thank you
