### ISSUE TITLE
Sometimes npcs stops chasing mobs when pushable trait is applied (doesn't always occur very random)

### ISSUE THREAD

**Issue by axemwa** [mcmonkeyprojects/Sentinel#278]
Title explains.

I'm Using latest Sentinel dev build to date

**Comment by axemwa** [comment]
Every other build works for me except 507

**Comment by axemwa** [comment]
how do i fix caching

**Comment by axemwa** [comment]
https://github.com/PaperMC/Paper/issues/1817

**Comment by axemwa** [comment]
oops sorry posted to wrong issue

**Comment by mcmonkey4eva** [comment]
`

I'm Using latest Sentinel dev build to date`
that's not a build number.

**Comment by axemwa** [comment]
Sorry was in a rush, by latest to date dev build I meant this one http://ci.citizensnpcs.co/job/Sentinel/
208

**Comment by mcmonkey4eva** [comment]
if you've used `/npc pushable -r` that will break navigation, beyond that, it shouldn't.

**Comment by axemwa** [comment]
I used /npc pushable -t at one point

**Comment by axemwa** [comment]
it's possible I might have done an `-r` typo at that time, I reapplied the sentinel traits and set everything back up for now anyway and  I'll let u know if I run into it again, will do some further testing soon.

**Comment by axemwa** [comment]
Found this, when an npc has the pushable trait I try to set linear paths but the npc just walks back an forth, but without pushable trait it functions normally

**Comment by axemwa** [comment]
uhh correction, when npc has the sentinel trait the npc walks back and forth instead of the set paths

**Comment by mcmonkey4eva** [comment]
Please verify that Spigot, Citizens, and Sentinel are are fully up to date
(Post output of `/version`, `/version citizens`, and `/version sentinel` ran in-game)

Also please post the NPC's data from `Citizens/saves.yml` (use pastebin)

**Comment by axemwa** [comment]
[06:59:44 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1612)
[06:59:44 INFO]: Website: http://www.citizensnpcs.co
[06:59:44 INFO]: Authors: aPunch and fullwall
------------------------------------------------------------------
[07:00:15 INFO]: Sentinel version 1.7.6 (build 208)
[07:00:15 INFO]: Author: mcmonkey
---------------------------------------------------
[07:01:18 INFO]: This server is running Paper version git-Paper-507 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Citizens - [saves.yml](https://pastebin.com/r48dCwuP) - NPC ID's 159 & 146 (Guards/succubusqueen)

**Comment by mcmonkey4eva** [comment]
on both npcs
you have:
`
      mounttrait:
        mountedon: 7cd499f6-097c-4fbf-b358-dd23e7fd3659
`
You have other npcs also seemingly mounted on that uuid.

NPC 159 has a really weird path (it has two points in a row that are barely 1 block apart, which is likely to bug)
It also does not have any targets - I guess you're trying to make it rely purely on fightback? There's a lot of situations in which temporary targets (from 'fightback') might be dropped. If you want to make it keep fighting a target, you have to actually add a target to the npc.

**Comment by axemwa** [comment]
i temporarily took targeting off before I sent the yml my bad, this still happens with targets set though

**Comment by axemwa** [comment]
plus these are old NPCs thaty have been on th server for a while maye something changed in the updates that affected them aswell?

**Comment by mcmonkey4eva** [comment]
Closing as a suspected user issue, not anything wrong with Sentinel.

... Also, using the pushable trait on a Sentinel NPC is pretty dumb to begin with. Sentinel NPCs are pushable by default.

**Comment by axemwa** [comment]
I'm just reporting what I see just incase, not blaming the plugin or anything bad. The pushable trait added itself for some reason I did not add it and same goes for the npc's mounting each other. I'm no longer using sentinels atm as busy with other things but when i use them again and find the issue again ill try find a easy way for u to reproduce it cause these settings seem to apply themselves sometimes.

**Comment by mcmonkey4eva** [comment]
Traits don't apply themselves.

**Comment by axemwa** [comment]
well the mount trait did, I did not set that. Unless it auto applies when you sit?
