### ISSUE TITLE
sentinel needammo false not working for crackshot

### ISSUE THREAD

**Issue by alex6456** [mcmonkeyprojects/Sentinel#279]
The output of command `/version` on my server is: **(This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **( Citizens version 2.0.24-SNAPSHOT (build 1612))**
The output of command `/version sentinel` on my server is: **(Sentinel version 1.7.6 (build 213))**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(https://pastebin.com/mXLymNXf)**
i want them to have ammo but they just run out and don't do shit
https://pastebin.com/prcT4Kby

**Comment by mcmonkey4eva** [comment]
That functionality isn't available for the CrackShot integration.

You should give Sentinel NPCs weapons that won't run out (I believe there's a way to control this stuff in the CrackShot config)
