### ISSUE TITLE
Plugin constantly calls events

### ISSUE THREAD

**Issue by TerZer** [mcmonkeyprojects/Sentinel#281]
Using latest version of Sentinel, Citizens and paper spigot 1.12.2. Configs are irrelevant.
I was making my own plugin and noticed something weird with InventoryCloseEvent, after a little bit of research I have came up with conclusion that Sentinel plugin calls InventoryCloseEvent every 7-8 seconds.

**Comment by mergu** [comment]
And has your conclusion led you to the source code calling this event? Was your conclusion formed on a server with no plugins other than Sentinel and Citizens? Does your conclusion have reproducible, tangible steps to follow?

**Comment by mcmonkey4eva** [comment]
Please provide any information at all, as mentioned above ^
Including versions and reproduction as mentioned, and probably stacktraces of the event being called that clearly show Sentinel as the originating source.
Will reopen when that information is provided.

**Comment by TerZer** [comment]
I simply was unloading plugin after plugin from server and find out, that Sentinel is calling close event. After that I checked if this actually Sentinel and Citizens, and find out that is actually true. As you can see in this gif:
https://gyazo.com/36bf1008af3d35ebcbea70d4d02b095c.gif
It happens always.
Code to check if it calls InventoryCloseEvent:
`	@EventHandler
	public void onClose(InventoryCloseEvent e) {
		System.out.println("CLOSE EVENT CALLED ON PLUGIN A! Viewers: " + e.getViewers().size());
	}`

PaperSpigot 1.12.2 build: 1596
Sentinel: Sentinel-1.7.6-b207
Citizens: Citizens-2.0.24-b1615

The Sentinel config and Citizens are pregenerated, nothing is changed. But I have some npcs with traits:
https://pastebin.com/1eUR8fNM

**Comment by mergu** [comment]
No, you don't test this stuff using Plugman. It's notorious for breaking things. You test this by fully restarting your server.

Reproduce on a server with **only** Citizens, Sentinel, and a tiny plugin with just that event in it. If you can't, it's a plugin conflict. If you can, we can revisit this.

**Comment by mcmonkey4eva** [comment]
Also, as mentioned in my previous comment, provide a stack trace.

**Comment by TerZer** [comment]
Reproduced on a server with only Citizens, Sentinel, and a tiny plugin with just that event in it and it still calls on close event. The thing is that close event is called then NPC is spawned and has traits on him. I already pasted my npc saves.

**Comment by mcmonkey4eva** [comment]
I'll just go ahead and copypaste myself:

Also, as mentioned in my previous comment, provide a stack trace.

**Comment by TerZer** [comment]
Ok. I fixed my problem. The thing was, that npc was dying and it was calling close event: https://pastebin.com/NHYVYamg
