### ISSUE TITLE
Could not pass event PlayerMoveEvent to Sentinel

### ISSUE THREAD

**Issue by dfsek** [mcmonkeyprojects/Sentinel#283]
The output of command `/version` on my server is: 
[Fri, 29. Mar 2019 04:37:15 UTC INFO] This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[Fri, 29. Mar 2019 04:37:15 UTC INFO] Checking version, please wait...
[Fri, 29. Mar 2019 04:37:16 UTC INFO] You are 89 version(s) behind
The output of command `/version citizens` on my server is: 
[Fri, 29. Mar 2019 04:37:49 UTC INFO] Citizens version 2.0.24-SNAPSHOT (build 1604)
[Fri, 29. Mar 2019 04:37:49 UTC INFO] Website: http://www.citizensnpcs.co/
[Fri, 29. Mar 2019 04:37:49 UTC INFO] Authors: aPunch and fullwall
The output of command `/version sentinel` on my server is: 
[Fri, 29. Mar 2019 04:38:19 UTC INFO] Sentinel version 1.8.5 (build 238)
[Fri, 29. Mar 2019 04:38:19 UTC INFO] Author: mcmonkey
A pastebin.com link to my `Sentinel/config.yml` file is: https://pastebin.com/NyYT06Hf

Every once in a while, the message `[ERROR] Could not pass event PlayerMoveEvent to Sentinel v1.8.5 (build 238)` is spammed in the server console many times per second, and slows down the server. 
The message does not stop unless the server is restarted or if there are no players on the server. I encountered the same problem without the "workaround" options enabled in the config, and enabled them hoping it would solve the problem.
It seems to be an issue with respawning the Sentinel, as it seems to start after one of them dies, and if the respawn time is set using Citizens, (not Sentinels) then the errors only occur until the NPC is respawned.

**Comment by mcmonkey4eva** [comment]
Please update Sentinel, Citizens, and Spigot. All 3 are outdated.
