### ISSUE TITLE
Npc's wont target event:pvp/pve/pvnpc and so on

### ISSUE THREAD

**Issue by Bisdakikobe** [mcmonkeyprojects/Sentinel#285]
The output of command `/version` on my server is: **(CraftBukkit version-git-Spigot-db6de12-18fbb24 (MC: 1.8.8) Implementing API version 1.8.8-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **(2.0.24-Snapshot (build 1628) )**
The output of command `/version sentinel` on my server is: **(1.8.5 (build 242) )**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(https://pastebin.com/N8Qqfvdv)**

https://pastebin.com/LTqDMu5M

also npc's wont work as a squad although I add the same squad name to each of them

**Comment by mcmonkey4eva** [comment]
Please update your server to one released more recently than 5+ years ago.
https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by Bisdakikobe** [comment]
I also tried that and it doesn't seem to work wit 1.13 1.13.2 either

**Comment by mcmonkey4eva** [comment]
Please post the output of command `/version`
And also update Sentinel to latest dev build: https://ci.citizensnpcs.co/job/Sentinel/

**Comment by Bisdakikobe** [comment]
Craftbukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2)
(Implementing  API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
I've replicated this issue and will fix

**Comment by mcmonkey4eva** [comment]
fixed in builds DEV-249+

**Comment by Bisdakikobe** [comment]
Great ! everything seems to be working properly now thanks !
