### ISSUE TITLE
Npc's wont target event:pvp/pve/pvnpc and so on 1.13.2

### ISSUE THREAD

**Issue by Bisdakikobe** [mcmonkeyprojects/Sentinel#286]
The output of command /version on my server is: (CraftBukkit Spigot(MC: 1.13.2)
The output of command /version citizens on my server is: (2.0.24-Snapshot (build 1628) )
The output of command /version sentinel on my server is: (1.8.5 (build 242) )
A pastebin.com link to my (full!) Sentinel/config.yml file is: (https://pastebin.com/N8Qqfvdv)

https://pastebin.com/LTqDMu5M

also npc's wont work as a squad although I add the same squad name to each of them

**Comment by mcmonkey4eva** [comment]
Duplicate issue, please post more detailed information to #285 rather than opening a new issue
