### ISSUE TITLE
Citizens spawn/teleport somewhere far away from their spawnpoints

### ISSUE THREAD

**Issue by Bisdakikobe** [mcmonkeyprojects/Sentinel#287]
The output of command /version on my server is: (CraftBukkit Spigot(MC: 1.13.2)
The output of command /version citizens on my server is: (2.0.24-Snapshot (build 1628) )
The output of command /version sentinel on my server is: (1.8.5 (build 249) )
A pastebin.com link to my (full!) Sentinel/config.yml file is: (https://pastebin.com/Q11zVpfr)
citizens saves: https://pastebin.com/4fti0GAz
basically NPC's despawn randomly and spawn in a vicinity of each other somewhere far from where their spawnpoints are or where the essentials plugin spawnpoints are they also can't be teleported back sometimes if u dont tp to them and select them while standing next to them also my Warden npc got deleted on its own P.S I am not sure if thats when it occured but I noticed it when adding Matrix Anticheat and updating ProtocolLib to the latest 4.4 and yes there are WG regions with entry=deny but that didn't stop them before

**Comment by mcmonkey4eva** [comment]
Any form of entry deny should be considered suspicious - Please test whether it's the cause (ie disable that temporarily and see if the problem goes away)

AntiCheats can also be suspicious in some cases (if it mistakes the NPCs for real players, it might think the NPC is "cheating" by teleporting and responds by moving them away). If the entry=deny test doesn't get anywhere, please also try removing that plugin temporarily to see if that fixes it.

**Comment by Bisdakikobe** [comment]
I tried removing the Anticheat plugin then I brought it back because it didnt make a difference and the thing is that it teleports even static Npcs and the ones who never enter the entry=deny zones
and by "please also try removing that plugin temporarily to see if that fixes it." do you mean removing world guard ?

**Comment by mcmonkey4eva** [comment]
` the thing is that it teleports even static Npcs and the ones who never enter the entry=deny zones`
That's actually not relevant. Please test removing that setting.
`do you mean removing world guard ?` I was referring to the anticheat plugin on that line.

**Comment by Bisdakikobe** [comment]
before removing the anticheat I managed to get them to spawn 5/8 on 1 of the locations where the other 3 are being spawned underground and 0/3 in another place 
after removing the anti cheat there is no change in the results after trying to restart the server or to perfrom /citizens reload to test it

**Comment by mcmonkey4eva** [comment]
Are you going to test removing `entry=deny` or...?

**Comment by Bisdakikobe** [comment]
well its about 30 regions so i need to remove the whole plugin

**Comment by mcmonkey4eva** [comment]
temporarily removing the entire plugin would also function to test it

**Comment by Bisdakikobe** [comment]
well just tested it and its even a bit worse

**Comment by Bisdakikobe** [comment]
well it seems to not be saving spawnpoint settings and their path  because some of them get fixed and do save but some wont I also try /citizens save and restarting the server

**Comment by Bisdakikobe** [comment]
deleting these npc's and copying the ones which worked seems to fix it for now

**Comment by mcmonkey4eva** [comment]
Try the general steps listed on https://wiki.citizensnpcs.co/Plugin_Conflict
