### ISSUE TITLE
Sentinels look down when attacking

### ISSUE THREAD

**Issue by Ferocimo** [mcmonkeyprojects/Sentinel#289]
The output of command `/version` on my server is: **Paper version git-Paper-624 (MC: 1.13.2)**
The output of command `/version citizens` on my server is: **2.0.24-SNAPSHOT (build 1631)**
The output of command `/version sentinel` on my server is: **version 1.8.5 (build 250)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/rYmtummk**

Hello,

As said in title, sentinels always look down when attacking, like [this](http://www.noelshack.com/2019-18-6-1556970089-2019-05-04-13-41-14.png). Once there foe is defeated, they will continue to look down, like [this.](http://www.noelshack.com/2019-18-6-1556969460-2019-05-04-13-30-39.png)

Thank you for looking into this, or, if this is a Citizens pathfinding issue, letting them know of it.

**Comment by mcmonkey4eva** [comment]
Can't replicate this on current versions (Spigot 1.14, Citizens `2.0.25-SNAPSHOT (build 1671)`, Sentinel `1.9.1 (build 253)`).
Advise updating at minimum Citizens and Sentinel to latest dev builds each and testing.
Also advise testing on Spigot 1.13.2 (instead of Paper 1.13.2)

**Comment by Ferocimo** [comment]
We did further tests and found out it was due to "workaround entity chase pathfinder" config option set to true (as you can see in the config posted). We used that some time ago to work around issues with water, but it seems to be okay now. 

Anyway, so you can know, this option causes this bug.

**Comment by mcmonkey4eva** [comment]
That's a Citizens issue somewhat, but I can fix it in Sentinel so why not, I've done so.
Fix is in build DEV-257+

**Comment by Blamo27** [comment]
@mcmonkey4eva Same issue with the build 2.0.1-SNAPSHOT (build 342)
