### ISSUE TITLE
sentinel drops

### ISSUE THREAD

**Issue by DenisJ9798** [mcmonkeyprojects/Sentinel#291]
Spigot 1.12.2
Citizens v2.0.24
sentinel 191
I have Not receive the item after killing the NPC, why?

**Comment by mcmonkey4eva** [comment]
You might have blocked drops in your server (via gamerule or some plugin's settings)
Consider enabling `workaround drops` in the config: https://github.com/mcmonkeyprojects/Sentinel/blob/master/src/main/resources/config.yml#L55-L56
