### ISSUE TITLE
Locking this issue as you seem disinterested in providing replication info for the original error, and instead are just posting unrelated nonsense.

### ISSUE THREAD

**Issue by DenisJ9798** [mcmonkeyprojects/Sentinel#293]
Locking this issue as you seem disinterested in providing replication info for the original error, and instead are just posting unrelated nonsense.

_Originally posted by @mcmonkey4eva in https://github.com/mcmonkeyprojects/Sentinel/issues/292#issuecomment-493791440_
What information do you need?

**Comment by mcmonkey4eva** [comment]
Cease posting. If you post a new issue (or at least one like this) I will contact GitHub staff.

As you can't handle GitHub issues, might I suggest the Discord? https://discord.gg/Q6pZGSR
