### ISSUE TITLE
Anchor/escort npc by npc

### ISSUE THREAD

**Issue by thunderai** [mcmonkeyprojects/Sentinel#294]
The output of command `/version` on my server is: 

Paper 28 1.14.1

The output of command `/version citizens` on my server is:

2.0.25 build 1692

The output of command `/version sentinel` on my server is:

1.9.1 build 253

A pastebin.com link to my (full!) `Sentinel/config.yml` file is:

https://pastebin.com/x9RhED0x

A). Add ability to have NPC escort or guard other NPCs. Have them support each other as a squad.

Thank you.

**Comment by mcmonkey4eva** [comment]
Added to build 268+ on https://ci.citizensnpcs.co/job/Sentinel/
Use `/sentinel guard npc:[id]` like `/sentinel guard npc:5`
