### ISSUE TITLE
send to coordinates

### ISSUE THREAD

**Issue by Vohldizar** [mcmonkeyprojects/Sentinel#295]
The output of command /version on my server is:

Paper 28 1.14.1

The output of command /version citizens on my server is:

2.0.25 build 1692

The output of command /version sentinel on my server is:

1.9.1 build 253

A pastebin.com link to my (full!) Sentinel/config.yml file is:

https://pastebin.com/x9RhED0x

Would it be possible to add the ability to send the sentinels to specific coordinates? even over great distances and over water?

**Comment by mcmonkey4eva** [comment]
Not a Sentinel issue.

**Comment by mcmonkey4eva** [comment]
If you want to _teleport_ an NPC, there's ways in Citizens itself to do that.

If you want an NPC to walk away over great distances, you need an separate meta-pathfinder plugin for that.
