### ISSUE TITLE
Suggestion: Protect an Animal

### ISSUE THREAD

**Issue by wuCenterless** [mcmonkeyprojects/Sentinel#297]
Protect animals and fight back

**Comment by mcmonkey4eva** [comment]
That in itself is just `event:pve`

The thing to add (per original request made by Spigot DM) would be defending specific examples (in the original request, chickens)

**Comment by mcmonkey4eva** [comment]
Added to build 273+ https://ci.citizensnpcs.co/job/Sentinel/

Use `/sentinel addtarget event:pv:chicken` (or whichever mob type).
