### ISSUE TITLE
/trait Sentinel not working.

### ISSUE THREAD

**Issue by gc2023** [mcmonkeyprojects/Sentinel#298]
The output of command `/version` on my server is: **[15:14:26 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **[15:14:55 INFO]: Citizens version 2.0.16-SNAPSHOT (build 1267)
[15:14:55 INFO]: Website: http://www.citizensnpcs.co
[15:14:55 INFO]: Authors: aPunch and fullwall**
The output of command `/version sentinel` on my server is: **[15:15:10 INFO]: Sentinel version 1.9.1 (build 253)
[15:15:10 INFO]: Author: mcmonkey**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/eVVDapME**

Now, describe your issue or feature request below.
**When I do /trait Sentinel It says "Please report this error: [See Console] and I get an error. Paste bin link below.**
If you have any error messages or relevant server logs, please include them via pastebin.
**https://pastebin.com/cFGaM8Ak**
If an NPC is misbehaving in any way,
**No**
please include the section of `Citizens/saves.yml` with the save details for that NPC via pastebin.

**Comment by gc2023** [comment]
Sentinel works with that version of Citizens when I use Sentinel 1.8.5

**Comment by mcmonkey4eva** [comment]
Update to latest Sentinel: https://ci.citizensnpcs.co/job/Sentinel/
And latest Citizens: https://ci.citizensnpcs.co/job/Sentinel/

Please also consider updating your actual server to a more recent version of Minecraft: https://wiki.citizensnpcs.co/Minecraft_1.8
