### ISSUE TITLE
Able to pick up sentinel arrows

### ISSUE THREAD

**Issue by PsychoLynx** [mcmonkeyprojects/Sentinel#299]
The output of command `/version` on my server is: **CraftBukkit version git-Spigot-df0eb25-efd8a2b (MC: 1.14.2)**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1704)**
The output of command `/version sentinel` on my server is: **1.9.2 (build 262)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **Should be default, but here you go https://pastebin.com/gisfRJXc**

I am able to pick up arrows fired by Sentinels equipped with a bow, using latest spigot, Citizens and Sentinel, no other plugins on the server. No config files have been touched.

**Comment by mcmonkey4eva** [comment]
See here's the thing...
I can easily replicate this, arrows are indeed being picked up.
However I know for sure in the semi-recent past that wasn't possible.
And I verified for sure just now that this line of code runs:
https://github.com/mcmonkeyprojects/Sentinel/blob/c74f82eec150dbfe1832f52bf6672191793a1b56/src/main/java/org/mcmonkey/sentinel/SentinelWeaponHelper.java#L81

... and yet I can replicate it.
I do believe this is a Spigot bug.

**Comment by mcmonkey4eva** [comment]
It appears that `setShooter` breaks the pickup status (within Spigot's code) for some reason.
I've reordered the code execution to handle this. Should be fine now (in build DEV-263+)
