### ISSUE TITLE
1.14 server crash

### ISSUE THREAD

**Issue by Momonche** [mcmonkeyprojects/Sentinel#300]
The output of command `/version` on my server is: Paper build 123 (1.14.3)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1718)
The output of command `/version sentinel` on my server is: 1.9.2 (build 263)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/4N505DkG

I just update my server on 1.14.3 and I have a lot of crash because of Sentinel NPC
https://timings.aikar.co/?id=443ac309a5ba4dcba9b1b8e9b5d4e1fd
But there is no error in the console

**Comment by mcmonkey4eva** [comment]
What crash? How is Sentinel related? Is there a crash log?
This just looks your server is lagging... which, that's what happens when you run Paper 1.14.x
Run Spigot 1.14.3, or even better run 1.13.2.
