### ISSUE TITLE
Sentinel throwing warnings into console whenever anything happens involving the plugin.

### ISSUE THREAD

**Issue by VirtualPixel** [mcmonkeyprojects/Sentinel#302]
The output of command `/version` on my server is: [15:33:56 INFO]: This server is running Paper version git-Paper-147 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[15:33:56 INFO]: Previous version: git-Paper-134 (MC: 1.14.3)
[15:33:56 INFO]: You are 1 version(s) behind
(It's the newest version, don't know why it says I'm 1 version behind.)

The output of command `/version citizens` on my server is: [15:34:50 INFO]: Citizens version 2.0.25-SNAPSHOT (build 1732)
[15:34:50 INFO]: Website: http://www.citizensnpcs.co
[15:34:50 INFO]: Author: fullwall

The output of command `/version sentinel` on my server is: [15:35:11 INFO]: Sentinel version 1.9.2 (build 261)
[15:35:11 INFO]: Author: mcmonkey

A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/6s9qTFHP

Anytime we interact with Sentinel through commands or if they attack mobs, it throws warnings.

Here is what happens in the console when the "/sentinel addtarget monster" command is typed - https://pastebin.com/eUhZg3uv

Here is what comes into the console when the NPCs attack a mob - https://pastebin.com/CvDV6U30

**Comment by mcmonkey4eva** [comment]
The errors are thrown by a plugin named `Ultimate_Economy`

I would recommend simply removing that plugin entirely and replacing it, it appears even just in its naming to completely fail to obey basic Java standards.
