### ISSUE TITLE
Suggestion: attack entity on player attack

### ISSUE THREAD

**Issue by Dinoseto** [mcmonkeyprojects/Sentinel#303]
Would be nice to have player guards attack whatever player is attacking (for example, player A with guard attacks player B, so player A guard adds player B on his target list until player B dies).

I'm doing the suggestion here as you suggested in the spigot forums :)

**Comment by mcmonkey4eva** [comment]
Added to Sentinel build 271+ https://ci.citizensnpcs.co/job/Sentinel/
Use `/sentinel addtarget event:guarded_fight`
