### ISSUE TITLE
Sentinels with Crackshot Weapons Firing 1 Block Too Low

### ISSUE THREAD

**Issue by kagaminecyn** [mcmonkeyprojects/Sentinel#304]
MC: Spigot 1.14.3
Citizens: 2.0.25-SNAPSHOT (build 1719)
Sentinel: 1.9.2 (build 261)

Issue: Sentinels shooting guns have difficulty shooting spiders. Gun-shooting sentinels appear to shoot 1 block lower than the entity's height, so since a spider is 1 block tall, the Sentinel keeps trying to shoot into the ground _under_ the spider, so it can't hit the spider. Make targeting 1 block higher for Crackshot-shooting Sentinels please?

**Comment by mcmonkey4eva** [comment]
That's... odd. The internal code specifically aims directly towards the target's eye location (ie `ent.getEyeLocation()`). It might just be a really weird eye location for spiders?

**Comment by mcmonkey4eva** [comment]
Tested locally, Sentinel with a CrackShot gun ('carbine') is able to perfectly hit spiders. Aim does not appear to be wrong for any mob types.

**Comment by mcmonkey4eva** [comment]
Need sufficient information to recreate the issue before I can do anything about it.
