### ISSUE TITLE
Feature request to add "helditem:ANY" target so that it can be added to the "addignore" list so that targets and avoids can be set for players holding a specific item instead of just any item

### ISSUE THREAD

**Issue by axemwa** [mcmonkeyprojects/Sentinel#306]
Feature request to add "helditem:ANY" target so that it can be added to the "addignore" list so that targets and avoids can be set for players holding a specific item instead of just any item

Example:

/sentinel addignore allinone:player|helditem:any
/sentinel addavoid allinone:player|helditem:.*sword

This way when the player equips a sword and the npc runs away, when the player switches to another item that isn't a sword the NPC will stop running.

**Comment by mcmonkey4eva** [comment]
As you can see by your own second example line: the input accepts a RegEx.
Therefore `ANY` would be just `.*`.
I believe the regex for 'anything BUT a sword' would be `^((?!sword).)*$`, per https://www.regextester.com/15

**Comment by axemwa** [comment]
wow thanx I didn't even think of that
