### ISSUE TITLE
How would I add "nation" targetting support for Towny?

### ISSUE THREAD

**Issue by Steffbeard** [mcmonkeyprojects/Sentinel#308]
Currently, you can only target individual towns but I want to make it so you can target entire nations

I would use the
`code`
thing but it's not formatting properly for me so here's the code in a pastebin

https://pastebin.com/qBBNXQmh

What am I doing wrong? I am not very good at making plugins but I thought I could try and add this in

**Comment by mcmonkey4eva** [comment]
Not quite up to free Java tutoring at the moment (and to be honest, based on your attempt there, you'd need tutoring in the pure basics).
I've gone ahead and added nation support myself for you, it's in build 282+
