### ISSUE TITLE
Don't greet too much

### ISSUE THREAD

**Issue by skerit** [mcmonkeyprojects/Sentinel#310]
I would love for sentinels to have several greetings to be chosen at random but, especially, to only use a greeting once per specified time range, maybe 1 minecraft day.

My friendly sentinel is standing at the door of a shop, so every time you go through the door he says his greeting.

**Comment by mcmonkey4eva** [comment]
While this could be added to Sentinel,
You might want to check out Denizen: https://www.spigotmc.org/resources/denizen.21039/
It'd be pretty simple to write a Denizen script that handles the greeting the way you want it.

**Comment by mcmonkey4eva** [comment]
Added `/sentinel greetrate RATE` to build DEV-307+ on https://ci.citizensnpcs.co/job/Sentinel/

Thanks for the suggestion!
