### ISSUE TITLE
NPC makes hits with no damage and no knockback

### ISSUE THREAD

**Issue by R4zzerYT** [mcmonkeyprojects/Sentinel#311]
Video from that bug is here:
https://youtu.be/rA5FKRi_Sbc

**Comment by mcmonkey4eva** [comment]
Extremely likely to be a plugin conflict. Refer to https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by R4zzerYT** [comment]
maybe a anticheat issue?
