### ISSUE TITLE
Ignore event handler corrections

### ISSUE THREAD

**Issue by OverlordWeaponry** [mcmonkeyprojects/Sentinel#313]
The output of command `/version` on my server is: Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1754)
The output of command `/version sentinel` on my server is:1.9.5 (build 281)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/iL72u08v

So while working with Sentinel, I noticed that any custom damage that I wanted the sentinel to inflict via the Damageable#damage(num, sent#getLivingEntity()); was automatically set to whatever the damage value for the trait was (In my case, I have it set to 0). However, this is something that I do NOT want to happen. Do you think there could be a setting where the plugin does not perform event corrections?

**Comment by mcmonkey4eva** [comment]
Options:
A: Change the Sentinel NPC's damage value to whatever you need
B: Don't do weird manual damage in the first place
C: Don't source your custom damage to an NPC that isn't actually inflicting the damage
