### ISSUE TITLE
Allow Sentinel to not retarget

### ISSUE THREAD

**Issue by OverlordWeaponry** [mcmonkeyprojects/Sentinel#314]
For Sentinel,

I love sentinel, but the biggest complaint I have with it right now is that every time the runUpdate() occurs, it selects a new closest target.

If possible, it would be very useful to me if once it has a target, it does not retarget unless it is specified a new target or the target is dead or out of range.

**Comment by mcmonkey4eva** [comment]
Added config option `random.retain target`, set to `true` for this request.
