### ISSUE TITLE
Further integration with TownyAdvanced

### ISSUE THREAD

**Issue by MegaKerfuffle** [mcmonkeyprojects/Sentinel#315]
The output of command `/version` on my server is: Paper version git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1770)
The output of command `/version sentinel` on my server is: Sentinel version 2.0.0-SNAPSHOT (build 315)

While Sentinel does currently have support for targeting towns and nations for attacks, the Sentry feature of having NPC targets align with town/nation enemies is no longer available. It'd be much appreciated if this feature could find it's way back into Sentinel, so that NPCs can automatically adjust their town/nation targeting depending on what town they are aligned with/a part of.

Thanks

**Comment by mcmonkey4eva** [comment]
Standard policy is any issue that just says "add this thing that Sentry had" will be disregarded.

Please describe what you want in terms of what it actually is / should be, and how it would work within Sentinel.

**Comment by MegaKerfuffle** [comment]
I'm not entirely sure how it would work from a developer standpoint, but in essence: Allow NPCs to be members or residents of towns, and have their targeting parameters align to what town they are a part of. As an example, let's say we have an npc 'aligned' with Town A. Town B becomes enemies with Town A, and the npc now begins to target players (and maybe even other npcs) that are residents of Town B. Eventually, Town A makes peace with Town B and the npc stops targeting Town B residents. This could probably also be scaled up to the nation level as well, with town npcs aligning their targeting with the nation.

**Comment by mcmonkey4eva** [comment]
Don't need a developer standpoint, need a _user_ standpoint.
Not a *player* to be clear, a *user*. Somebody who is directly using Sentinel. What do they do? Is there a target type that user might make use of?
You've mentioned: towns can be enemies of other towns, and suggested aligned-targeting based on this. So perhaps there'd be some form of target type that amounts to "enemies of town (name)", like `townenemies:(TOWN_NAME)`?

**Comment by MegaKerfuffle** [comment]
Yeah, that's pretty much exactly what I'm looking for, where the user would be able to set a sentinel target based on the enemies of a town. `townenemies:(TOWN_NAME)` is probably the ideal way of putting it. `nationenemies:(NATION_NAME)` could also be a possible flag for larger scale targeting.

**Comment by mcmonkey4eva** [comment]
Did a bit of research on Towny for this feature request.
As far as I can tell: The situation you described simply isn't how Towny works.
A town cannot be enemies with another town. Only nations can make enemies with each other.

I've added `nationenemies:NATION_NAME` and `nationallies:NATION_NAME` as new target types.

If my quick research is wrong and towns can actually become enemies each other, please provide a link to documentation on that concept (in the Towny wiki or wherever else that explains how that works).
