### ISSUE TITLE
Skeleton Arrow Stays on NPC

### ISSUE THREAD

**Issue by cwchristerw** [mcmonkeyprojects/Sentinel#316]
![2019-12-07_02 55 36-2](https://user-images.githubusercontent.com/13464896/70366050-3e289300-189d-11ea-83fb-8e8ae85b4980.png)

To get arrows to disappear I have to do /npc despawn and /sentinel respawn

The output of command `/version` on my server is: 
**This server is running CraftBukkit version
git-Spigot-1981d55-3e7b386 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT
Checking version, please wait...
You are 68 version(s) behind**
The output of command `/version citizens` on my server is: 
**Citizens version 2.0.25-SNAPSHOT (build 1781)
Website: http://www.citizensnpcs.co
Author: fullwall**
The output of command `/version sentinel` on my server is: 
**Sentinel version 2.0.0-SNAPSHOT (build 315)
Author: mcmonkey**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is:
**https://pastebin.com/6ESmVtRN**

**Comment by mcmonkey4eva** [comment]
Is this issue specific to Sentinel-type NPCs, or just any NPC?

**Comment by mcmonkey4eva** [comment]
Also, is this specific to arrows fired by a skeleton, or will a player-fired arrow also get stuck?

**Comment by cwchristerw** [comment]
Arrow will get stuck only when normal default vanilla skeleton shoots Sentinel NPC. Player shooted arrows disappear normally.

**Comment by mcmonkey4eva** [comment]
That answers the second, but not the first: Is this issue specific to Sentinel-trait NPCs, or just any NPC?

**Comment by cwchristerw** [comment]
Sentinel-trait NPC because skeletons doesnt shoot NPC's without Sentinel trait

**Comment by mcmonkey4eva** [comment]
Tested locally.
- Arrows shot by players still get stuck in NPCs, it is not skeleton specific.
- Arrows get stuck in non-Sentinel NPCs too, it is not Sentinel specific.
This is a Citizens issue.
