### ISSUE TITLE
swords turn into helmets

### ISSUE THREAD

**Issue by jed1** [mcmonkeyprojects/Sentinel#317]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1781)
The output of command `/version sentinel` on my server is: Sentinel version 2.0.0-SNAPSHOT (build 315)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/raw/BsT6AjgU

I have a really strange phenomenon:
my sentinel npcs are all equipped with iron swords and iron helmets, but when they start to attack they suddenly hold iron helmets, which is unfortunate because helmets aren't the best tool for cutting down zombies ;-)

**Comment by jed1** [comment]
I've tried to investigate this bug a little further and tried some different helmets and weapons. And it seems the problem is simply that sentinels just clone their helmets and replace their weapon with it. I've tried wooden axe and enchanted leather helmet and as soon as there is a target nearby the npc has the helmet both on its head and in its hand and the axe just vanished.

**Comment by mcmonkey4eva** [comment]
You've enabled `autoswitch` globally in your config (which is weird to do... you should probably use the commands for that, not the config...), which appears to be the functionality misbehaving here.

**Comment by mcmonkey4eva** [comment]
The backing code for autoswitch was a bit of a mess.
I've decided to just rewrite the logic for it.
In initial testing, it appears to work perfectly fine now with the rewritten logic.

The fix is in build DEV-325+ on https://ci.citizensnpcs.co/job/Sentinel/
