### ISSUE TITLE
when npc has a crackshot weapon in hand it does fight. Wtf?

### ISSUE THREAD

**Issue by telfrancesco** [mcmonkeyprojects/Sentinel#318]
The output of command `/version` on my server is: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1762)
The output of command `/version sentinel` on my server is: Sentinel version 2.0.0-SNAPSHOT (build 315)
https://pastebin.com/ZtUrx5WP

Hi, when i equip an Crackshot weapon an npc, it does not follow me (to fight) (wtf?) but. i equip an random item it follow me to fight (normal). Wtf)
https://www.youtube.com/watch?v=tiv_NoRBeo8 Please help me!

**Comment by SXRWahrheit** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by telfrancesco** [comment]
I tried with 1.12/1.13. It btw doesn't work.

**Comment by mcmonkey4eva** [comment]
`/sentinel chaseranged true`
Chasing is toggleable separately for ranged vs. melee, and defaults true for melee but false for ranged (generally you don't want bowmen or gunners running into melee range of their targets!)
