### ISSUE TITLE
A few NPC sentinels spawn in randomly without weapons

### ISSUE THREAD

**Issue by TheLastBlockbender** [mcmonkeyprojects/Sentinel#320]
The output of command `/version` on my server is: Paper version git-Paper-33 (MC:1.15.1)
The output of command `/version citizens` on my server is: 2.026-SNAPSHOT (build 1804)
The output of command `/version sentinel` on my server is: 2.0.1-SNAPSHOT (build 333)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/WKnucHK3

I have a couple NPC sentinels that have a respawntime set to 0, but spawn at seemingly random times when they have been despawned. They also spawn in without their equipped weapon. The only pattern I notice is that they all have bows. (No arrows). However not all sentinels with bows seem to have this problem.

Citizens save file: https://pastebin.com/mHmTRahj

**Comment by mcmonkey4eva** [comment]
That'd be a Citizens issue. Equipment persistence is handled by Citizens, and if sentinel respawn time is 0 then Sentinel isn't respawning it, you either have a Citizens respawn handler or a Denizen option or something (check https://github.com/mcmonkeyprojects/Sentinel#common-issues )

You have at least one NPC with the Denizen `health` trait, which has its own respawning system.
