### ISSUE TITLE
Add a shulker mob attack weapon

### ISSUE THREAD

**Issue by LArchitectt** [mcmonkeyprojects/Sentinel#323]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1829)**
The output of command `/version sentinel` on my server is: **Sentinel version 2.0.1-SNAPSHOT (build 339)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/C9L8G6wM**

The feature requested can enable the native attack of the Shulker.
Currently, the Shulker open itself when a target is in it's range, it deal damage but without any animation.

I want to enable the native fire of Shulker, with to possibity to edit fire rate of this attack too.

Thanks

**Comment by mcmonkey4eva** [comment]
Shulker bullets will now be used when you equip the NPC with a SHULKER_SHELL as a weapon
