### ISSUE TITLE
Gravity bug

### ISSUE THREAD

**Issue by fichdlmaa** [mcmonkeyprojects/Sentinel#324]
"Plugin attempted to register net.citizensnpcs.trait.Gravity@a18305d while not enabled"

The output of command `/version` on my server is: **(PLEASE FILL IN)**
1.14.4 (Final build; latest snapshot)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
Citizens 2.0.26 1.15.x BETA #1 as well as Version 2.0.26 build 1842

The output of command `/version sentinel` on my server is: **(PLEASE FILL IN)**
2.0.1-Snapshot Build 339 as well as build 338, 337, a.s.o.

A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(PLEASE FILL IN)**
** I beg your pardon. All my pastebin slots are in use. Only 10 allowed at the same time  :-( 
  - I have to wait 8 more days until I can delete some of them **

....
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register net.citizensnpcs.trait.Gravity@a18305d while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:552)
	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
	at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:234)
	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:419)
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:603)
	at net.minecraft.server.v1_14_R1.World.a(World.java:745)
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:379)
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068)
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:552)
	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
	at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:234)
	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:419)
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:603)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC)
	Entity ID: 1995
	Entity Name: Pollux
	Entity's Exact location: 4.46, 66.00, 5.43
	Entity's Block location: World: (4,66,5), Chunk: (at 4,4,5 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_14_R1.World.a(World.java:745)
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:379)
...

__________ saves.yml "Pollux" - START ___________________________
....
  '87':
    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE1NzkwODUwNTgxNTIsInByb2ZpbGVJZCI6ImIxNjcxM2FhNGI4ZjQzMzRiNmJhMzZkY2E1MTZjMTJhIiwicHJvZmlsZU5hbWUiOiJQb2xsdXgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E4Njg2NzhkZjMzMmNhNjQzNDk3NTljMmYzNjc1MzhjZDg4YTFhNGYzZTRiZTBlYmJjYmM1OWNkZGU5YTQzMTQifX19
      cached-skin-uuid-name: pollux
      cached-skin-uuid: b16713aa-4b8f-4334-b6ba-36dca516c12a
      player-skin-signature: V7ltTvK67xGTEiqjdpvtBBfXX+Abijw2PNYh0+HnqsOqLgZcxTUma7q7UlivdJWwyOlTayWWRUQDIguJ6DQp1mVIYpMn0RDK/g5fWUCa3YHj2QBzPmyyskEbz2oK0wORh80HWzEsvQUKtp0n5B+Bd/0QkY+TyyIHga4jkWjhOU6rs1KGt2G8ADX0n4Xyfs0D0GpZrs+vd6SqJxDmrLMPxGVOZ0vKNa9fdQN0GlJQjXdKR0ZSmUlZwv6jnD/+jiKIW073nP7S22ShwN6ccbVI+wjEHQLKWgRkFmkmdQQDg+eGgOWESYz0UbPLCZKzRP5TvXVeK2nUoUWFKtgRxLh4BY44jbgVrLXA8uM6A/p5TuxIoX5g2FHcpB5KDTCvYmDxpFSr3CG5jb6r90fEcJF+XDtfhaYOFQeDUuNRzCrPbPnxHq1A8/l3BQQBK3/E5uiqru6QgY+iPmbKf7DKTD3zt/75SQDzu3q2MAuRdVinf8EqU4Xgv+pKY841XnnjsOwQGEjIgIOam20k5Ki6IT3R10Noh/HwbPm6BB2o50v3SYtL4mS5EiHUxEhAKMKosw6gak57t85J4f+WBo794XnqHuOln8HAEgklfhjSn5AH2lcR5uGJoN0+ZYptQ9nT7RS3eITekECctME8CqxThZ4vtKXQWP4N9ahb7n6orooaTJg=
    name: Pollux
    uuid: 1baba0b4-5bd5-44a3-941f-762ba8142fc3
    traits:
      lookclose:
        range: '5.0'
        enabled: true
        enableRandomLook: false
        randomLookDelay: 60
        realisticlooking: true
        randomPitchRange:
          '0': -10.0
          '1': 0.0
        randomYawRange:
          '0': 0.0
          '1': 360.0
      equipment:
        helmet:
          type_namespace: minecraft
          type_key: iron_helmet
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterhelm
          enchantments:
            blast_protection: 4
            thorns: 3
            respiration: 3
            aqua_affinity: 1
        chestplate:
          type_namespace: minecraft
          type_key: iron_chestplate
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterharnisch
          enchantments:
            thorns: 3
            projectile_protection: 4
        leggings:
          type_namespace: minecraft
          type_key: iron_leggings
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterbeinschutz
          enchantments:
            thorns: 3
            fire_protection: 4
        boots:
          type_namespace: minecraft
          type_key: iron_boots
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterstiefel
          enchantments:
            thorns: 3
            protection: 4
            feather_falling: 4
            depth_strider: 3
            aqua_affinity: 1
      trader:
        guiName: waffenhändler
      location:
        world: kampfwelt
        x: '4.4598'
        y: '66.0'
        z: '5.4337'
        yaw: '163.1002'
        pitch: '0.0'
      inventory:
        '36':
          type_namespace: minecraft
          type_key: iron_boots
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterstiefel
          enchantments:
            feather_falling: 4
            thorns: 3
            protection: 4
            aqua_affinity: 1
            depth_strider: 3
        '37':
          type_namespace: minecraft
          type_key: iron_leggings
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterbeinschutz
          enchantments:
            thorns: 3
            fire_protection: 4
        '38':
          type_namespace: minecraft
          type_key: iron_chestplate
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterharnisch
          enchantments:
            projectile_protection: 4
            thorns: 3
        '39':
          type_namespace: minecraft
          type_key: iron_helmet
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: true
            repaircost: 0
            displayname: Wächterhelm
          enchantments:
            respiration: 3
            thorns: 3
            aqua_affinity: 1
            blast_protection: 4
      spawned: true
      gravity:
        enabled: false
      type: PLAYER
      owner:
        owner: FichdlMaa
        uuid: 04b15309-4b83-41ff-a16f-2917d299eb97
    traitnames: scoreboardtrait,owner,lookclose,gravity,type,mounttrait,trader,equipment,location,inventory,spawned
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
__________ saves.yml "Pollux" - END ___________________________

Btw. Question:
" gravity:
        enabled: false" 
is default, isn't it? All my NPC have got this config entry like this ...

Greets

(Minecraft) FichdlMaa

**Comment by fichdlmaa** [comment]
Hm.

I already got (the same?) sentinel issue(s) some month ago with an older build of 1.14.4. The Server freezed/crashed as soon as I used sentinel plugin. Tried a lot of things - in vain. 
Then I did remove all my *moving* citizen npcs an after it worked again, I startet creating new ones ... 
Castor and Pollux are *non-moving* NPCs, too! They worked fine as trading NPCs (dtlTraders Plus) for several weeks now ... 

My Server works stable and fine with all plugins including citizens and dtlTraders Plus - except I use sentinel. I tried latest beta and latest and some older jenkins builds 33x ...

I will post complete Infos via pastebin next week (if still needed)

**Comment by mcmonkey4eva** [comment]
This has nothing whatsoever to do with Sentinel.
It's vaguely related to Citizens (not Sentinel) but isn't caused by Citizens. The error you posted is just a secondary error, not the initial problem that crashed your server. Most likely it was just server lag leading to a timeout crash, because you're on 1.14.x and 1.14.x is a broken minecraft version... update to 1.15.2

**Comment by fichdlmaa** [comment]
Hi McMonkey, tnx for fast reply.

OK. Ticket closed. No solution. -- But where I don't agree:

1. Server is fast and stable inclusive Citizens and dtlTradersPlus with more than a dozen of traders an some more citizen NPCs. As soon as I add sentinel, the bug occurs... 
You've right that Citizens seems not to be the problem, but we talk about sentinel, not citizens!

2. Spigot 1.14.4 is NOT a broken MC Version. Or do you mean the lack of bees? ;-)
Perhaps, sentinel has got a problem with latest 1.14.4 spigot. But with concern of about 15 other plugins working fine with it, the "broken" refers to sentinel on Spigot 1.14.4, not to 1.14.4 itself.

*** Please! - Don't see the above as personal attack! ***
Nowadays I only develop small utilities, but I can understand well you Spigot developers: Minecraft  release cycles have become very short since M$ bought Mojang. 
- Hard - to develop good AND fast enough for latest version (as long it is the latest) ... 
- Harder - to maintain several versions at the same time. ... 
- Hardest - to to this in spare time besides a job ...

Lucky developing! Keep up the good work!

Greets

FichdlMaa


P.S.: I will switch to 1.15.2 the next few weeks (some plugins still not stable for it); but I think 1.16 will be pre until then... 'til then I have to do without Senti ...

**Comment by mcmonkey4eva** [comment]
`Spigot 1.14.4 is NOT a broken MC Version. Or do you mean the lack of bees? ;-)`
Denial helps nothing.
Mojang, Spigot, Paper, etc. have all publicly acknowledged that 1.14.x was significantly broken.
It's not specific to Sentinel. It's not specific to Citizens. It's not related to plugins. It's Minecraft 1.14.x... which is a broken version.
Update to 1.15.2 if you want a working server. (You'd also be better off in 1.13.2 than 1.14.x for that matter, but downdating is silly when you can update instead)

`*** Please! - Don't see the above as personal attack! ***`
What your post *is* is ignorant and combative. Sentinel is not broken, on any version, and it's a pointless waste of everyone's time and energy to claim so as seemingly just an attempt to cast the blame on a random plugin instead of acknowledging that you need to update your server.
Regardless of where you try to throw the blame, the reality remains that Minecraft 1.14.x is a broken version, and the only fix to the stability issues encountered on it is to update to 1.15.2.
