### ISSUE TITLE
enforce damage issue

### ISSUE THREAD

**Issue by GermanMinersNET** [mcmonkeyprojects/Sentinel#326]
The output of command `/version` on my server is: **git-Spigot-2cf50f0-8166d17 (MC: 1.12.2)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1751)**
The output of command `/version sentinel` on my server is: **Sentinel version 2.0.1-SNAPSHOT (build 327)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/nHCfrpPd**

Hey there, I got a problem/bug with Sentinel.
If I set enforce damage to true in the config, sentinel npcs can also do damage to players in worldguard regions with the flag pvp = deny players. The problem is that the npcs can then no longer do any damage to mobs. They do attack the mobs, but no damage happens.
Unfortunately there are no error logs in the console.

**Comment by mcmonkey4eva** [comment]
Not able to replicate this problem.

Please test for a plugin conflict: https://wiki.citizensnpcs.co/Plugin_Conflict
