### ISSUE TITLE
NPCs not attacking

### ISSUE THREAD

**Issue by cantercrow** [mcmonkeyprojects/Sentinel#328]
The output of command `/version` on my server is: Paper version git-paper-243 MC 1.14.4
The output of command `/version citizens` on my server is: Citizens version 2.0.26-SnapShot (build 1792)
The output of command `/version sentinel` on my server is: Sentinel version 2.0.1-Snapshot (build 327)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/wKF9Hn8J

Now, describe your issue or feature request below.
If you have any error messages or relevant server logs, please include them via pastebin.
If an NPC is misbehaving in any way,
please include the section of `Citizens/saves.yml` with the save details for that NPC via pastebin.
-->

I am using NPC_Police and Sentinel to make NPC's attack players, I have noticed that NPC's with the trait sentinel and not attacking the my player which created the NPC even with /sentinel removeignore owner. Also the NPC is not attacking if the player is OP'd

**Comment by mcmonkey4eva** [comment]
As said in the issue template: Please pastebin the contents of `Citizens/saves.yml` and specify the IDs of the NPCs that demonstrate the problem.

Please also verify that the relevant player meets all the basic requirements to be a valid target at all:
- Not on the NPC's ignore list
- Not god mode, creative mode, or any other mode that would prevent you from being damaged anyway
- Not invisible
- In clear view of the NPC
- Either actually on the target list, or doing something that would trigger a target (eg engaging in pvp if `event:pvp` is a target)

Also: Is this a problem only with `NPC_Police` involved, or can you replicate it using Sentinel commands alone?
