### ISSUE TITLE
"Mobs"-sentinel damages to armored player issue

### ISSUE THREAD

**Issue by Hizarion** [mcmonkeyprojects/Sentinel#329]
- `/version` on my server is: **(git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT))**
- `/version citizens` on my server is: **(2.0.26-SNAPSHOT (build 1859))**
- `/version sentinel` on my server is: **(Sentinel version 2.0.1 SNAPSHOT (build 340))**
- 'Sentinel/config.yml` file is: **(http://pastebin.fr/61748)**

Hi, I hope I didn't forget anything.
So I've noticed an issue since I have updated my server to 1.15.2 (from 1.13).
I have an RPG server and there is some armor with "protection 18" enchant. There is some Citizens NPC as sentinel: "player" type NPC does normal damages to a player with a heavely enchanted armor (with "damage: 40 it does around 2 hearts of damage to a full protection 18 player), however "mobs" type NPC (such as zombies, pigmen or bees, but I think it's probably related to all mobs even if I have not tested all of them) does 0 damage even if I give them "damage 999", but it does to a player without armor.
I did not have this problem before (in 1.13).
Also, I have noticed something, when you are hit by number of Sentinel NPC in the same time, the damage are incredibly high and does not since to be additionated but multiplicated. That's not as disturbing as the previous issue but I thought it may could be interresting for you to know that.

Hoping that it was clear and I didn't miss any important element.
And sorry for my language, I'm french so my english is probably not perfect.

Thank you,
Hizarion.

**Comment by mcmonkey4eva** [comment]
A few users have said that's been a problem for them, however I have not been able to replicate it on a clean server.

I'd request you test a clean server and/or follow https://wiki.citizensnpcs.co/Plugin_Conflict to track down the problem.

If you're able to find what setting or plugin causes it to break, please do reply below with that information.

**Comment by Hizarion** [comment]
Switch the "enforce damage" from false to true in the config of Sentinel seems to have solved this issue, at least for me.
Thank you :)
