### ISSUE TITLE
Add Bedwars Support: Trader and Team support

### ISSUE THREAD

**Issue by asaasa123** [mcmonkeyprojects/Sentinel#330]
This server is running CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Citizens version 2.0.24-SNAPSHOT (build 1605) +CitizensText version 1.18
Sentinel version 1.0 (build 90)

https://pastebin.com/ZbVjwrYP

I have an idea: Support for bedwars. 
This gives away a lot of features such as: Make a Sentinel work for you AFTER Trading with him (such as paying him emeralds etc)
Make Guards NOT attack teammates, but only enemies (And more)!

**Comment by mcmonkey4eva** [comment]
Team targets/ignores: Can probably indeed do
"Make a sentinel work for you": That's a job for a Denizen script.

**Comment by asaasa123** [comment]
Okay, thank you for your time! But is the trader thing possible?

**Comment by mcmonkey4eva** [comment]
Possible with a Denizen script, yes.

**Comment by asaasa123** [comment]
> Possible with a Denizen script, yes.

Whoops, i read your comment incorrectly. So you can create the team support but the trait is something i must code with Denizen? Thanks!

**Comment by mcmonkey4eva** [comment]
Delayed response, but uh... what plugin is "BedWars"? A quick search reveals a small variety of different plugins offering the functionality of a bedwars gamemode
