### ISSUE TITLE
After remove Sentinel trait, the still track player and take damage

### ISSUE THREAD

**Issue by DevSrSouza** [mcmonkeyprojects/Sentinel#332]
Citizens Build: 1879
Sentinel Build: 341

Even after respawn without Sentinel, they still take damage and die.

https://media.giphy.com/media/kEboWcoAGgaV9HL7uk/giphy.gif
![](https://media.giphy.com/media/kEboWcoAGgaV9HL7uk/giphy.gif)

**Comment by mcmonkey4eva** [comment]
Fixed for build 342+
