### ISSUE TITLE
Make books cast Evoker spells

### ISSUE THREAD

**Issue by RJAcelite** [mcmonkeyprojects/Sentinel#334]
The output of command `/version` on my server is: Paper 1.14.4
The output of command `/version citizens` on my server is: Citizens v2.0.26
The output of command `/version sentinel` on my server is: Sentinel version 2.0.1 build 327
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/8rgvv7pF

As the title states it, this only applied to sentinels with certain items equipped. This idea came from the sentinel samples such as Blazerods casting Fireball, EnderPearl casting Sky toss, or NetherStar casting Thunder. I'm creating an NPC that can cast Evoker Fangs and Lazerbeam via certain item attached.

**Comment by mcmonkey4eva** [comment]
I don't think it's entirely accurate to vanilla behavior, but... there, book item now triggers an imitation of the evoker fang attack
