### ISSUE TITLE
Conflict with preciousstone

### ISSUE THREAD

**Issue by Grigorasz** [mcmonkeyprojects/Sentinel#336]
Hey! 
I have a small problem and I want to know if it can be fixed.
At the moment my pc cannot attack a player if it is under the protection of preciousstone.
I would like to know if something can be done to attack players even if the protection is anti-pvp

**Comment by mcmonkey4eva** [comment]
This is in the readme under the `common issues` section https://github.com/mcmonkeyprojects/Sentinel#common-issues
