### ISSUE TITLE
Prevent NPC from destroying blocks using witherskull.

### ISSUE THREAD

**Issue by RJAcelite** [mcmonkeyprojects/Sentinel#340]
The output of command /version on my server is: Paper 1.14.4
The output of command /version citizens on my server is: Citizens v2.0.26
The output of command /version sentinel on my server is: Sentinel version 2.0.1 build 327
A pastebin.com link to my (full!) Sentinel/config.yml file is: https://pastebin.com/8rgvv7pF

When NPC held Wither_Skull they act as the projectile used by the wither. Is there a way to turn off the block damage of the explosion without setting /gamerule mobgriefing to false? 
I mean sure mobs can have it on but I wanted it specifically for companion Sentinel NPC not to completely ruin the cave just for shooting a bat or skeleton without turning off the mobgriefing as that would eliminate other stuffs that make the game unique such as mobs picking up 
items or creepers ruining houses. So I suggest we have config options that turns off npcs from destroying blocks without having to toggle gamerule command.
I wanna add similar to blazerod the turns off fire tick without using gamerule dofiretick.

**Comment by mcmonkey4eva** [comment]
Added that as a Sentinel config option, defaults to enabled.

This is includedin build 352+ from https://ci.citizensnpcs.co/job/Sentinel/
