### ISSUE TITLE
Exception loading entity

### ISSUE THREAD

**Issue by Momonche** [mcmonkeyprojects/Sentinel#341]
The output of command `/version` on my server is: **git-Paper-284 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1957)**
The output of command `/version sentinel` on my server is: **2.1.0-SNAPSHOT (build 350)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/jWrQTzkU**

Hello !
I have this error happens sometimes and make a Sentinel IA broken when the chunk load : https://pastebin.com/eTEFng4S

Exemple of a NPC causing that : https://pastebin.com/wS3WTxT9

**Comment by mcmonkey4eva** [comment]
That looks like just a corrupt chunk, that happens to have been loaded as a result of a sentinel launching an arrow in the direction of the chunk

**Comment by Momonche** [comment]
Can I do something to prevent this ? Or can you du someting in the plugin ?

**Comment by mcmonkey4eva** [comment]
You can fix your corrupt chunks? This isn't caused by Sentinel at all, it's coincidental.
