### ISSUE TITLE
Enchantments on sword don't work with Sentinels

### ISSUE THREAD

**Issue by Ferocimo** [mcmonkeyprojects/Sentinel#343]
The output of command /version on my server is: git-Paper-343 (MC: 1.15.2)
The output of command /version citizens on my server is: 2.0.26-SNAPSHOT (build 1982)
The output of command /version sentinel on my server is: 2.1.0-SNAPSHOT (build 353)
A pastebin.com link to my (full!) Sentinel/config.yml file is: https://pastebin.com/gGwwJX9j

Hello, 

Previously when you gave swords with certain enchantments to Sentinel, the enchantments were effective when the Sentinel used the sword on players or mobs.

For instance when you gave a Knockback II sword to a Sentinel, entities hit by the Sentinel would be effectively knockbacked.

This is no longer the case for some time now. Although I'm not able to tell since when did that happen, I tested it with multiple enchantments and am positive of this (it's particularly visible with Fire Aspect since the target entity doesn't catch fire when hit).

Thank you for looking into this.

**Comment by mcmonkey4eva** [comment]
```
    # Whether to force damage through (particularly for ranged attacks).
    enforce damage: true
    # Whether to use 'workaround' mode of fist damage.
    workaround damage: true
```
^ These config values you have set will break weapon enchantments.
Change them back to `false` to fix that.

**Comment by Ferocimo** [comment]
@mcmonkey4eva These config values are the solutions to about a dozen other issues that we previously opened on Sentinel over the previous years. You actually specifically created "enforce damage" because of an issue we reported. 

If we have to change them to false, we will have to reopen all these issues.

We always had these values to true, and it previously worked with enchantments, so obviously something changed at some point.

**Comment by mcmonkey4eva** [comment]
If you can identify a specific build (from <https://ci.citizensnpcs.co/job/Sentinel/>) I might be able to do something... otherwise, resolution is change those to `false` and fix the problems on your server that ever required they be set `true`.

**Comment by Momonche** [comment]
I just try with Citizens build 1995 and Sentinel 355, with a default config (so workaround-damage and enforce-damage on false)

I create a Sentinel with a sword FireAspect 2 and I'm not on fire, same with KnockBack

**Comment by Ferocimo** [comment]
@mcmonkey4eva I strongly remember being able to put working enchantments on Sentinel, but I must be wrong since we tested it on every possible version since 1.8 and it didn't work. Maybe I remember it from Sentry.

However, this is an issue regarldess of enforce damage and workaround damage, as Momonche pointed out.

**Comment by Ferocimo** [comment]
@mcmonkey4eva Hello ?
