### ISSUE TITLE
AutoSwitch To Open Hand

### ISSUE THREAD

**Issue by blockprophet** [mcmonkeyprojects/Sentinel#345]
The output of command `/version` on my server is: CraftBukkit version git-Spigot-8fc58f1-50484a6 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2019)
The output of command `/version sentinel` on my server is: Sentinel version 2.1.5-SNAPSHOT (build 360)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/CWkWv6Qa

It would be very useful if NPCs with the sentinel trait could be configured to equip a weapon only once engaged in combat. A particular example from my server: the innkeep should be ready to defend his property from monsters and the like, but shouldn't just go about his activities passively wielding a sword. Thanks for considering!

**Comment by mcmonkey4eva** [comment]
Added this as default behavior when autoswitch is enabled
