### ISSUE TITLE
Lands Compatibility Request

### ISSUE THREAD

**Issue by DeadSeaHacks** [mcmonkeyprojects/Sentinel#346]
The output of command `/version` on my server is: >.... This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT
The output of command `/version citizens` on my server is: >.... Citizens version 2.0.27-SNAPSHOT (build 2067)
The output of command `/version sentinel` on my server is: >.... Sentinel version 2.1.5-SNAPSHOT (build 360)

A pastebin.com link to my (full!) `Sentinel/config.yml` file is:  https://pastebin.com/n4HqPv0y

Can we can get compatibility for [Lands](https://www.spigotmc.org/resources/lands-minecraft-land-claim-plugin-grief-prevention-protection-gui-management-wars-1-16-support.53313/) like we have with Massivecore Factions so that sentinel NPCs can target members of certain Lands and ignore members of certain Lands?

**Comment by mcmonkey4eva** [comment]
Thaaaat is a premium-only plugin. Sentinel cannot internally support plugins that cannot be publicly redistributed alongside Sentinel.

The developer of that plugin could add integration into Sentinel from their end if they're willing to.
