### ISSUE TITLE
Sentinels don't take damage on new world

### ISSUE THREAD

**Issue by ShadowWolf90** [mcmonkeyprojects/Sentinel#347]
The output of command `/version` on my server is: **git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2072)**
The output of command `/version sentinel` on my server is: **(2.1.5-SNAPSHOT (build 360))**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/i1jfUXAz**
Citizens saves: https://pastebin.com/rG5tvCDi

On new world created on my pc, and then uploaded to server, Sentinels don't receive damage from players.
I use Multiverse, and on older world, npcs normally take damage, what i done wrong?

**Comment by ShadowWolf90** [comment]
i'll try fix it with readme on github.

**Comment by ShadowWolf90** [comment]
All things that are in readme, doesn't work, Sentinels don't take any damage from players, in PvP zone, and no-PvP Zone.

**Comment by mcmonkey4eva** [comment]
If it's specifically only replicable on a world that multiverse created, it's a problem either with Multiverse or with that world.

So, check that world's config (Gamerules, difficulty, etc) for things that might interfere with player or mob damage and try disabling them (pvp false, difficulty peaceful, etc. could potentially be related).

If that isn't sufficient, try testing without multiverse (load that other world as the main world in `server.properties`, or load it through a different plugin, eg via the `createworld` command in Denizen). That will narrow down whether it's related to the world's settings or to the Multiverse plugin. (also, related wiki page: https://wiki.citizensnpcs.co/Plugin_Conflict )

**Comment by Sataniel98** [comment]
I have the same problem. Not with Multiverse, but with my own plugin. Sentinel NPCs don't take damage, no idea why.

**Comment by mcmonkey4eva** [comment]
That is not the same issue. Open a new one if needed.
