### ISSUE TITLE
Piglin issues in the overworld 

### ISSUE THREAD

**Issue by SuperPyroManiac** [mcmonkeyprojects/Sentinel#348]
The output of command `/version` on my server is: git-Paper-105  -  1.16.1
The output of command `/version citizens` on my server is: 2.0.27 Build 2056
The output of command `/version sentinel` on my server is: 2.1.5 Build 360
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/E8cbVmZQ

Piglins that are just regular NPC's work fine, but the second you add the sentinel trait to them, they start to freeze and turn into the pigzombie monsters, no longer an NPC but keep the nametag and gear.

**Comment by mcmonkey4eva** [comment]
This is a Citizens issue. It can be replicated without Sentinel using just `/npc vulnerable`
