### ISSUE TITLE
1.16.2 Support Aternos

### ISSUE THREAD

**Issue by Steel-Zika** [mcmonkeyprojects/Sentinel#350]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
The output of command `/version sentinel` on my server is: **(PLEASE FILL IN)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(PLEASE FILL IN)**

**Comment by Steel-Zika** [comment]
![image](https://user-images.githubusercontent.com/70367633/91542196-be0bf700-e91d-11ea-965c-f5703a117ff4.png)

**Comment by Steel-Zika** [comment]
/version citizens 
![image](https://user-images.githubusercontent.com/70367633/91542260-d714a800-e91d-11ea-8614-126cbc45859e.png)

**Comment by Steel-Zika** [comment]
/version sentinel 
![image](https://user-images.githubusercontent.com/70367633/91542275-e09e1000-e91d-11ea-88c4-5210d8413eca.png)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Frequently_Asked_Questions#I_have_a_free_server_.28Aternos.2C_Minehut.2C_....29_but_there.27s_problems
