### ISSUE TITLE
Llama spit support

### ISSUE THREAD

**Issue by evelyn-f-king** [mcmonkeyprojects/Sentinel#352]
The output of command `/version` on my server is: **(PLEASE FILL IN)** Paper-186
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** 2114 (2.0.27)
The output of command `/version sentinel` on my server is: **(PLEASE FILL IN)** 2.2.0 (373)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(PLEASE FILL IN)**

https://one.denizenscript.com/haste/76486

NPCs cannot be made to shoot llama spit

**Comment by mcmonkey4eva** [comment]
Looks a bit ridiculous, but... equip an NPC with WHITE_DYE to make it shoot deadly llama spit at things.
