### ISSUE TITLE
Axe and shield. 

### ISSUE THREAD

**Issue by TermitCG** [mcmonkeyprojects/Sentinel#353]
The output of command `/version` on my server is: **git-Paper-231 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2149)**
The output of command `/version sentinel` on my server is: **2.2.0-SNAPSHOT (build 373)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/ZtJ57CTe**

When I attack sentinel with an axe, my NPC still can use his shield. There should be a cooldown.

**Comment by mcmonkey4eva** [comment]
Added a replica of vanilla axe shield breaking
