### ISSUE TITLE
Endermans can't be angry without moving

### ISSUE THREAD

**Issue by DarkBoow** [mcmonkeyprojects/Sentinel#354]
Hi, the last weekend I was trying to make a minecraft video thumbnail in minecraft. I wanted to create a stuck angry enderman but I could not manage to do that because when npc enderman are angry their body doesnt change to the angry mode, instead of the basic enderman creature when we look at him.

Can you please fix that for the angry enderman npc ?
And Thanks for advance for all the great work

Cordially,
DarkBow_

**Comment by mcmonkey4eva** [comment]
Using Sentinel for that is kinda weird, you should probably just use Denizen and the `enderman_angry` mechanism...

But, either way, added enderman anger to NPCs.

**Comment by DarkBoow** [comment]
Oh, thanks
