### ISSUE TITLE
Sentinels can destroy items in item frames

### ISSUE THREAD

**Issue by Tyloon1e** [mcmonkeyprojects/Sentinel#357]
The output of command `/version` on my server is: **This server is running Tuinity version git-Tuinity-"cc34294" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2191)**
The output of command `/version sentinel` on my server is: **Sentinel version 2.2.0-SNAPSHOT (build 377)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/raw/SKGYZFsF**

Saves: https://pastebin.com/raw/Z3zwaVgR

My Sentinels are able to destroy items in item frames with their arrows, if using a bow.
![image](https://user-images.githubusercontent.com/52511724/102012560-7df54680-3d4b-11eb-9b71-88256b300b05.png)

**Comment by mcmonkey4eva** [comment]
I'm fairly surprised that it took so long for somebody to have this happen (or, I guess: to *notice* it happening).
Fixed for build 379+ https://ci.citizensnpcs.co/job/Sentinel/

All non-living entities are now undamageable by Sentinel attacks including projectiles.

**Comment by Tyloon1e** [comment]
Great support as always. Thanks for being out there!
