### ISSUE TITLE
Config to disable special weapons 

### ISSUE THREAD

**Issue by SkytAsul** [mcmonkeyprojects/Sentinel#359]
The output of command `/version` on my server is: **git-Paper-391 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2186)**
The output of command `/version sentinel` on my server is: **2.2.0-SNAPSHOT (build 382)**

I'd like to see some configuration or NPC options to enable/disable special weapons actions (like shooting fireballs with blaze rods). In my case, that's because I'm retexturing items like the blaze rod to give them unique skins, but they behave like swords. However, my sentinels will shoot fireballs with an item designed to be a sword, so it's not really good ^^'

**Comment by mcmonkey4eva** [comment]
You can just do `/sentinel weaponredirect blaze_rod diamond_sword` (which will tell Sentinel to treat a blaze_rod like it's a diamond_sword, naturally)

**Comment by SkytAsul** [comment]
Ohhh nice, I didn't knew we could do that! Much thank you ^^
