### ISSUE TITLE
Add tab-complete for commands

### ISSUE THREAD

**Issue by SkytAsul** [mcmonkeyprojects/Sentinel#360]
The output of command `/version` on my server is: **git-Paper-391 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2186)**
The output of command `/version sentinel` on my server is: **2.2.0-SNAPSHOT (build 382)**

As Sentinel is using the Citizens command management system, would it be possible to use as well the tab-complete feature? It would be very useful.

**Comment by mcmonkey4eva** [comment]
Ooo, good point! Thank you for mentioning this.
Added via the commit above for build 385+ on https://ci.citizensnpcs.co/job/Sentinel/
