### ISSUE TITLE
Add an options to when sentinel finishes fighting goes back to its spawn point

### ISSUE THREAD

**Issue by telfrancesco** [mcmonkeyprojects/Sentinel#361]
The output of command /version on my server is: This server is running Paper version git-Paper-196 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

The output of command /version citizens on my server is:  Citizens version 2.0.27-SNAPSHOT (build 2113)
The output of command /version sentinel on my server is:  Sentinel version 2.2.0-SNAPSHOT (build 373)

Add an option when sentinel finishes fighting goes back to its spawn point (Ex. when finishes fighting (outside from spawn) a mob goes back to server's spawn)
-->

**Comment by mcmonkey4eva** [comment]
Can't add an option for what already exists.

As it says in multiple places in the readme, just set a point with `/npc path` to mark a return-to point
