### ISSUE TITLE
Plugin support for simplepets

### ISSUE THREAD

**Issue by Ltghavoc** [mcmonkeyprojects/Sentinel#363]
The output of command `/version` on my server is: git-paper-428 (MC: 1.16.5) (Implemeting API version 1.16.5-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2247)
The output of command `/version sentinel` on my server is: 2.2.0-SNAPSHOT (build 373)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/AZ8qk1hE

Requesting plugin support to allow for target ignoring of pets created using the simplepets plugin.  As it stands sentinels will kill any pets made from mobs types that they have targets for. I.E. If a sentinel has a target setting for zombies it will attack a zombie pet. For obvious reasons, I wouldn't call this a bug as it is technically working correctly but it makes many pets useless when sentinels are around.

We have managed to come to a workaround using the setting below but this only works as long as someone doesn't change their pets name.  /sentinel addignore entityname:[a-zA-Z0-9_]{3,16}'s\s(.+)\spet

**Comment by mcmonkey4eva** [comment]
The SimplePets code is a bit of a mess, but I think I've added a working integration. Haven't tested it though.

Works by added target: `simplepet:PET_NAME_REGEX`

So to just ignore all pets, do: `/sentinel addignore simplepet:.*`
