### ISSUE TITLE
QualityArmory Integration

### ISSUE THREAD

**Issue by DerLinkman** [mcmonkeyprojects/Sentinel#365]
Hello,

i was wondering if you could add a QualityArmory integration (such as the CrackShot one) to the Sentinel Plugin?

Link to QA: https://www.spigotmc.org/resources/quality-armory.47561/
It has a API, but im not a dev...

Greetings
DerLinkman

**Comment by mcmonkey4eva** [comment]
QA already has its own integration into Sentinel. This is even mentioned in the Sentinel readme.
