### ISSUE TITLE
[bug]npc can hurt god mode players

### ISSUE THREAD

**Issue by hkkongou** [mcmonkeyprojects/Sentinel#366]
The output of command `/version` on my server is: This server is running Purpur version git-Purpur-1158 (MC: 1.16.5)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT build 2316
The output of command `/version sentinel` on my server is: 2.2.6 SNAPSHOT build 411
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://paste.gg/p/anonymous/db4ed72a47dc4770a6203ea45cf84c16

hi, i have essentialX installed, one of my admin was testing sentinel npc, and we found out that god mode cannot prevent sentinel trait npc do damage on players, the essentials god mode should have able to block all damage from any source, it does block damage from void and mythicmobs real damage skills even in survival mode or adventure mode.

not sure why sentinel npc can still deal damage to players in survival god mode. This is the only way i found so far which can damage players when they are in god mode.

**Comment by mcmonkey4eva** [comment]
Sentinel uses the same Bukkit APIs to cause damage as any other plugin would (unless you enable the `workaround damage` or `enforce damage` options in the config).
If the NPC is a zombie or skeleton entity type, it will actually use the same method call as vanilla minecraft even.

If Essentials god mode isn't working for damage from Sentinel NPCs, I don't think there's much I could do to change that.
