### ISSUE TITLE
Equip CrackShot Guns via Command

### ISSUE THREAD

**Issue by Hexivoid** [mcmonkeyprojects/Sentinel#374]
It would be extremely useful if there was a way to equip Sentinel NPCs with CrackShot weapons outside of manually running /npc equip, i.e. especially in cases where NPCs and Sentinels are created via console. Please correct me if I'm wrong, but I believe there's currently no other way to equip weapons other than a player needing to do so by hand? 

Much appreciated.

**Comment by mcmonkey4eva** [comment]
Write a Denizen script + use the `equip` command + probably an item script to represent whatever additional data CrackShot needs.
https://guide.denizenscript.com/
