### ISSUE TITLE
Help! My NPC's Disappear as soon as It starts to walk. 

### ISSUE THREAD

**Issue by SpartianKing** [mcmonkeyprojects/Sentinel#379]
Zero Screenshot

The output of command `/version` on my server is: **(1.18.2)**
The output of command `/version citizens` on my server is: **(1.18.2)**
The output of command `/version sentinel` on my server is: **(1.18.2)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(Dont Have one)**

 My issue is that every time I spawn a NPC, I get it all configured correctly, and then it just starts walking and disappears. I dont know what is wrong because I get no errors, and I have no idea what would be wrong. Please reveiw the code...

**Comment by mcmonkey4eva** [comment]
Sounds like a Citizens issue, not Sentinel.

Also consider asking for help on Discord @ https://discord.gg/Q6pZGSR
