### ISSUE TITLE
Armor/weapon lose durability when used by NPCs

### ISSUE THREAD

**Issue by UEDCommander** [mcmonkeyprojects/Sentinel#380]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.29-SNAPSHOT (build 2520)**
The output of command `/version sentinel` on my server is: **Sentinel version 2.5.0-SNAPSHOT (build 461)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/Y7iLDqkB**

Grettings,
Im not particularly sure whether its a bug, an oversight or simply a feature not added yet, but when my sentinel'ed NPCs are fighting, particularly in close combat, their items seem to be losing durability with no clear way to affect this behaviour. That presents a problem, seeing as a lot of those NPCs are meant to be respawning guards/bosses that dozens of players will be fighting on a daily basis, which would mean that we would have to manually replenish their equipment (especially armor) from time to time. Seems strange, considering there is a setting that allows NPCs to not spend ammo when using ranged weapons.

**Comment by mcmonkey4eva** [comment]
You seem to have things backwards.
`needammo` ENABLES using of ammo and reducing of durability.
It by default is OFF.

If you've enabled needammo, then, there's your problem, turn it off.
If you haven't enabled that and you're seeing durability go down, something external is reducing them - likely another plugin, refer to https://wiki.citizensnpcs.co/Plugin_Conflict

If you need help tracking it down, make a thread in the Sentinel channel on Discord @ https://discord.gg/Q6pZGSR
