### ISSUE TITLE
Sentinel commands wont run

### ISSUE THREAD

**Issue by petefairman** [mcmonkeyprojects/Sentinel#384]
The output of command `/version` on my server is: Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
The output of command `/version citizens` on my server is: Citizens version 2.0.30-SNAPSHOT (build 2702)
The output of command `/version sentinel` on my server is: Sentinel version 2.3.0-SNAPSHOT (build 416)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/K1HhBj54
<!--
None of the Sentinel commands will run, the server message says it's an internal issue. How do I fix it?

**Comment by mcmonkey4eva** [comment]
Ask on Discord @  https://discord.gg/Q6pZGSR  in the #sentinel channel
