### ISSUE TITLE
Problem with MythicLib

### ISSUE THREAD

**Issue by YKDZ** [mcmonkeyprojects/Sentinel#386]
The output of command /version on my server is: git-Purpur-1777 (MC: 1.19.2)
The output of command /version citizens on my server is: Citizens version 2.0.30-SNAPSHOT (build 2765)
The output of command /version sentinel on my server is: Sentinel version 2.7.1-SNAPSHOT (build 499)
A pastebin.com link to my (full!) Sentinel/config.yml file is: https://pastebin.com/fkpDKPU9

This error will appear when sentinel attack by monsters or players etc.
https://pastebin.com/0UFYGiMN
Should I send this issue to MythicLib?

**Comment by mcmonkey4eva** [comment]
Yes, that's a mythiclib error
