### ISSUE TITLE
Console Error Upon Loading Latest Sentinel Version 2.0.30

### ISSUE THREAD

**Issue by BboyZeroOne** [mcmonkeyprojects/Sentinel#387]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
`[01:53:49 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-220 (MC: 1.19.2)`

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
`[01:54:28 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2767)
[01:54:28 INFO]: Website: https://www.citizensnpcs.co
[01:54:28 INFO]: Author: fullwall`

The output of command `/version sentinel` on my server is: **(PLEASE FILL IN)**
`[01:55:07 INFO]: Sentinel version 2.7.2-SNAPSHOT (build 501)
[01:55:07 INFO]: Author: mcmonkey`

A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(PLEASE FILL IN)**
https://pastebin.com/1PefYvTP

Error on console upon starting up Sentinel.
https://pastebin.com/W3fmZRYD
https://pastebin.com/YtqEDkXm

**Comment by mcmonkey4eva** [comment]
Actually, I pushed a new dev build to experimentally enable 1.19.2 back-compat
