### ISSUE TITLE
Bot will not switch weapon if the weapons have empty enchantment

### ISSUE THREAD

**Issue by skbeh** [mcmonkeyprojects/Sentinel#389]
The output of command `/version` on my server is: **PandaSpigot 1.8.8**
The output of command `/version citizens` on my server is: **2.0.30-SNAPSHOT (build 2816)**
The output of command `/version sentinel` on my server is: **2.7.2-SNAPSHOT (build 502)**

The bot will not automatically switch the weapon if the weapons have empty enchantment.
For example, if the bot have used a blaze rod to fire fireballs and a diamond sword is in its inventory, it will use blaze rod to hit the player when the bot runs close to the player instead of the sword.

Steps to reproduce:
1.
```
/npc create test_bot
/trait sentinel
/sentinel autoswitch true
/sentinel removeignore owner
```
2.
```
/give @p minecraft:diamond_sword 1 0 {ench:[{}]}
/give @p minecraft:blaze_rod 1 0 {ench:[{}]}
```
4. Use `/npc inventory` to put the items created above into the bot's inventory.

**Comment by mcmonkey4eva** [comment]
So... the issue is that if you spawn invalid items on your custom 8 year old server jar, there's a small misdetection issue?

Idk what you expect. Let me know if you can replicate it with valid items on a modern server.
