### ISSUE TITLE
 LuckPerms cannot safely respond to the request

### ISSUE THREAD

**Issue by ShadySt** [mcmonkeyprojects/Sentinel#391]
The output of command `/version` on my server is: **git-Purpur-1915 (MC: 1.19.3)**
The output of command `/version citizens` on my server is: **2.0.30-SNAPSHOT (build 2935)**
The output of command `/version sentinel` on my server is: **2.7.2-SNAPSHOT (build 502)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: [https://pastebin.com/QDMhCLir](https://pastebin.com/QDMhCLir)

Everytime my Sentinel NPC doing damage to other mobs I receive warns in console. Could you check, is it Sentinels fault or maybe Citizens or LuckPerms itself?
Pastebin link to some of the warns: [https://pastebin.com/uymLNmgP](https://pastebin.com/uymLNmgP)
Pastebin link to saves.yml: [https://pastebin.com/iwhrhAZq](https://pastebin.com/iwhrhAZq)

**Comment by mcmonkey4eva** [comment]
` b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups' to true in the LuckPerms configuration file.`

This is more properly a WorldGuard fault, however WorldGuard has explicitly refused to address bugs that involve Citizens for some unclear reason, despite this being very easily resolved.

Refer to Discord thread https://discord.com/channels/315163488085475337/1075169065372491776/1075169065372491776 ( https://discord.gg/Q6pZGSR )
