### ISSUE TITLE
NPC doesn't avoid danger, keeps teleporting or stops responding.

### ISSUE THREAD

**Issue by ShadowWolf90** [mcmonkeyprojects/Sentinel#393]
The output of command `/version` on my server is: Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
The output of command `/version citizens` on my server is: 2.0.32-SNAPSHOT Build 3188
The output of command `/version sentinel` on my server is: 2.8.0-SNAPSHOT Build 508
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/RQM1YkKZ

My NPC stopped avoiding any added entity. It doesn't run away or anything. It only punches if gets too close (sometimes).
If NPC follows player or tries to reach target (by following or by attacking) it teleports or randomly stops moving.

(Link to NPC config: https://pastebin.com/SXbyqU4P)

**Comment by mcmonkey4eva** [comment]
Please use the `#sentinel` channel on Discord @ https://discord.gg/Q6pZGSR
