### ISSUE TITLE
addtarget for whole squad

### ISSUE THREAD

**Issue by Biongar** [mcmonkeyprojects/Sentinel#400]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-477 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1207162)**
The output of command `/version citizens` on my server is: **2.0.33-SNAPSHOT (build 3381)**
The output of command `/version sentinel` on my server is: **2.8.1-SNAPSHOT (build 513)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **I don't have pastebin and looks like you won't need it**

**Comment by Biongar** [comment]
We need the ability to change the target/ignore for a group of NPCs at once, for example the whole /squad squad_foo addtarget player:bar

Is this possible?

**Comment by mcmonkey4eva** [comment]
https://forum.denizenscript.com/resources/multi-npc-command.58/

**Comment by Biongar** [comment]
Thank you, sorry for spending your time, I wasted 2 weeks but I didn't find anything
