### ISSUE TITLE
NPC is invisible after respawn

### ISSUE THREAD

**Issue by AndyNoob** [mcmonkeyprojects/Sentinel#403]
The output of command `/version` on my server is: **This server is running Paper version 1.21-66-master@99ae7bb (2024-07-14T13:40:23Z) (Implementing API version 1.21-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.35-SNAPSHOT (build 3475)**
The output of command `/version sentinel` on my server is: **Sentinel version 2.9.1-SNAPSHOT (build 523)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/HsR6SJ4b**

NPC, after respawning, is invisible. 
![invis npc](https://github.com/user-attachments/assets/53a51e4a-bc6e-49c7-91dc-767b4b02b0a5)

**Comment by mcmonkey4eva** [comment]
Citizens topic, not Sentinel - ask in https://discord.gg/Q6pZGSR
