### ISSUE TITLE
Integration with War?

### ISSUE THREAD

**Issue by PsychoLynx** [mcmonkeyprojects/Sentinel#65]
Hey! I was trying to set up a War battlefield with NPCs, however as I've discovered Sentinels don't seem to share the same compatibility with the War-plugin that Sentry did. Or at least it's not documented where I could have found it. Anyway, if they are not compatible, I would like some sort of compatibility.

Thank you!

**Comment by mcmonkey4eva** [comment]
What would war compatibility entail exactly?

**Comment by PsychoLynx** [comment]
Well, the most important thing I can think of thus far is for players to be able to attack NPCs of the opposing team - as now War just prints out the message "Your target is not playing in the Warzone" - another thing, I guess, would be to make NPCs's death drain a team's life pool (or not, as that might end up making things a little too different in the arena).

I must admit, I am not an expert when it comes to War, so I don't know all of its NPC fineries (nor are they documented anywhere afaik).

**Comment by PsychoLynx** [comment]
I should also point out that during my tests, I found out that if you have War installed on the server, it makes all ranged sentinels unable to hurt you (unless they have fire arrows, in which case the fire is what hurts you, not the arrow hitting you) even when the NPCs are not in a warzone. Melee sentinels work as usual.

**Comment by Jabelpeeps** [comment]
@PsychoLynx While you are waiting for mcmonkey to implement this, you could always try my re-write of Sentry:- https://github.com/Jabelpeeps/Sentries which is attempting to maintain the old functions, before adding new ones.  There is a link to the builds on my CI server in the ReadMe.  Let me know how you get on.

**Comment by mcmonkey4eva** [comment]
I'm thinking of starting looking into this myself soon.
But in reply to your most recent message @PsychoLynx , there's a new config option related to that, `enforce damage` ( https://github.com/mcmonkey4eva/Sentinel/blob/master/src/main/resources/config.yml#L52 ) which might help with that.

**Comment by mcmonkey4eva** [comment]
I'm messing with war and not sure how you want this done.

Like, perhaps, `/sentinel warteam gold` and they're in the gold team for all purposes then on, or...?

**Comment by PsychoLynx** [comment]
Well, I'm not sure how it works on the code level, but I think the sentinels need to be part of a team on the warzone so they can be attacked by players in the zone. But what you suggested sounds about right.

**Comment by mcmonkey4eva** [comment]
TBH I'm still pretty confused as to how to accomplish this, both in terms of design and code...

**Comment by PsychoLynx** [comment]
Hey! Sorry for the delayed reply - I had people on the server working out what we would like to see in terms of integration (in practice, I am afraid I can't help with the code questions :c). Here's ä list in order of relätive importänce.

* Assign Sentinels to attack/ignore certain War teams.
* Killing Hostile / Other team Sentinels = Optional gaining of points and vice versa.
* Friendly Sentinels optionally counting towards team minplayers
* Sentinels reset (respawn/are returned back to their original locations) upon map restart/reset.
* Making it so that a team can consist of only Sentinels (Such as ones hostile to everyone -  make an option that this team cannot win the round)
* Animal type Sentinels bypassing the no creatures flag?
* Monuments healing Sentinels as well?
* Sentinel will remember if it is supposed to guard an area upon spawning (return there after chaserange runs out)
* Conditional spawning of sentinels (such as entering an area)?
* Something like assign Sentinels & their gear on map while building -> Spawn them upon map loading -> removed & targets forgiven upon map end. Rinse and repeat. Optional respawns of Sentinels during the map (isn't this in sentinel already?)

**Comment by mcmonkey4eva** [comment]
(Almost a year later, sorry)
I've been ignoring this because it's just such a massive and complex request that I have little ability to test.

I'm open to pull requests for any of it of course, if any developers want to try integrating it..,

**Comment by mcmonkey4eva** [comment]
Latest builds (DEV-224+) contain a `war_team` target option.

The rest of that stuff, I think is a bit out of scope for Sentinel to contain directly.

I'd accept a PR for that, and would gladly help the War developers if they want to add support for Sentinel interaction into War.

Beyond that... `war_team` is what I got. If you can think of any integrations that you'd like to see that fit within the scope of Sentinel, please let me know.

**Comment by PsychoLynx** [comment]
Thank you kindly!
